/**
 * The colour picker: a hue ring round a saturation/brightness map, the hex,
 * presets, and — where the colour becomes an accent or an agent's colour — the
 * ink Stoke will actually paint with on this theme.
 *
 * Every colour field in the app opens it: an agent's colour (AgentsSettings),
 * the theme editor's accent and token overrides (through ColorField), and a
 * profile's colour (ProfilesSettings, which also keeps its swatch row).
 *
 * The maths is `@shared/colorPicker`, where `verify:color` can reach it. What
 * lives here is the behaviour, and each rule has a reason:
 *
 *  - A WORKING value, previewed live and committed once. Dragging fires a
 *    pointermove per frame; each one writing settings.json would be gotcha
 *    63's slider again. `onPreview` gets at most one colour per animation
 *    frame and writes nothing; `onCommit` is called once, on Enter, Done, an
 *    outside click, focus leaving, or unmount (the Settings sheet closes by
 *    unmounting, with no blur — gotcha 63's flush). Escape and Cancel revert:
 *    the preview is withdrawn and nothing is committed.
 *  - Pointer capture on the ring and the map, so a drag that leaves the
 *    control keeps steering it; a press jumps straight to the point.
 *  - Both are sliders a keyboard can drive (`stepHue`, `stepSv`), named for a
 *    screen reader by `colorName`.
 *  - Portalled into the dialog it was opened from (or the body), `position:
 *    fixed`, flipped and clamped into the window by `placePopover` — the
 *    Settings pane scrolls and clips, and a popover inside it would be cut in
 *    half. Registered with `useFloatingLayer` (gotcha 14), since a fixed layer
 *    can land over the docked browser.
 *
 * Its own chrome is CSS custom properties only. The colours it SHOWS — the
 * pick, the presets, the ring — are data, painted inline; the ring's gradient
 * is generated by `hueRingGradient` so no hex is written here.
 */
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState, type CSSProperties } from 'react'
import { createPortal } from 'react-dom'
import { agentTokensFor, clearanceFloor, reservedNear, type ReservedName } from '@shared/agentColors'
import { deriveAccent } from '@shared/accent'
import { profileAccentFor } from '@shared/profiles'
import {
  colorName,
  hexToHsv,
  hsvToHex,
  hueAt,
  hueName,
  hueRingGradient,
  inkShift,
  parseTyped,
  placePopover,
  pureHue,
  sameColor,
  stepHue,
  stepSv,
  svAt,
  typedIsComplete,
  type Hsv
} from '@shared/colorPicker'
import { useFloatingLayer } from '../lib/floatingLayers'
import { readRootTheme } from '../lib/rootTheme'
import { IconEyedropper } from './Icons'

export interface ColorPreset {
  name: string
  hex: string
}

/**
 * What the pick becomes, for the "on this theme" preview. An agent (or an
 * account key) is drawn as its tab tag; an accent as text and a filled chip;
 * a profile as its chip, with the colour it is stored as.
 */
export type InkPreview =
  | { kind: 'agent'; key: string; tag: string }
  | { kind: 'accent' }
  | { kind: 'profile'; name: string }

export interface ColorPickerProps {
  /** The swatch it opened from: where it is placed, and where focus returns. */
  anchor: HTMLElement | null
  /** The committed colour when it opened. */
  value: string
  /** What is being picked, e.g. "Claude Code colour". */
  label: string
  presets?: readonly ColorPreset[]
  /** Offers "Reset to default" while the pick differs from it. */
  defaultValue?: string
  ink?: InkPreview | null
  /** Live, unsaved: at most once a frame while the pick moves; null withdraws it. */
  onPreview?: (hex: string | null) => void
  /** Once, when the pick is kept and differs from `value`. */
  onCommit: (hex: string) => void
  /** The picker is done (kept or reverted); the owner unmounts it. */
  onClose: () => void
}

const RING = hueRingGradient()

/** What a reserved colour is, in words, for the picker's warning. */
const RESERVED_WORDS: Record<ReservedName, string> = {
  'meter-low': 'the context meter’s green',
  'meter-mid': 'the context meter’s orange',
  'meter-high': 'the context meter’s red',
  danger: 'the error red',
  warning: 'the gold a waiting tab pulses in'
}

interface EyeDropperLike {
  open(): Promise<{ sRGBHex: string }>
}
type EyeDropperCtor = new () => EyeDropperLike

/** Chromium's EyeDropper, where this Electron has one (feature-detected, never assumed). */
function eyeDropperCtor(): EyeDropperCtor | null {
  return (window as unknown as { EyeDropper?: EyeDropperCtor }).EyeDropper ?? null
}

/** Screen pixels off the swatch, and kept from the window's edge. */
const GAP_REM = 0.375
const EDGE_PX = 8

export function ColorPicker({
  anchor,
  value,
  label,
  presets,
  defaultValue,
  ink,
  onPreview,
  onCommit,
  onClose
}: ColorPickerProps): React.JSX.Element {
  const original = useRef(value)
  const [hsv, setHsv] = useState<Hsv>(() => hexToHsv(value) ?? { h: 0, s: 0, v: 0 })
  const hex = hsvToHex(hsv)
  /** The hex field while it is being typed in; null shows the pick. */
  const [typed, setTyped] = useState<string | null>(null)
  const [bad, setBad] = useState(false)
  const drag = useRef<'ring' | 'map' | null>(null)

  const popRef = useRef<HTMLDivElement>(null)
  const ringRef = useRef<HTMLDivElement>(null)
  const holeRef = useRef<HTMLSpanElement>(null)
  const mapRef = useRef<HTMLDivElement>(null)
  useFloatingLayer(popRef, true)

  const latest = useRef({ hex, typed, onPreview, onCommit, onClose, anchor })
  latest.current = { hex, typed, onPreview, onCommit, onClose, anchor }

  /** Set once the pick is kept or reverted; nothing after that commits. */
  const done = useRef(false)
  /** Whether a preview went out, so a revert knows to withdraw it. */
  const previewed = useRef(false)

  const setFromHex = useCallback((next: string): void => {
    setHsv((prev) => hexToHsv(next, prev) ?? prev)
  }, [])

  /**
   * Keep or revert, once. `pick` overrides the working value for the one
   * caller that has a newer one than the last render (Enter in the hex field);
   * a hex still being typed counts too, when it parses — an outside click
   * lands before the field's own blur, so "#abc" typed and clicked away from
   * would otherwise be dropped for the colour before it.
   * Focus goes back to the swatch only for a close the user made here —
   * Enter, Escape, Done, Cancel — never for a click somewhere else, which is
   * where they meant focus to go.
   */
  const finish = useCallback((keep: boolean, refocus: boolean, pick?: string): void => {
    if (done.current) return
    done.current = true
    const now = latest.current
    const kept = pick ?? (now.typed !== null ? parseTyped(now.typed) : null) ?? now.hex
    if (keep) {
      if (!sameColor(kept, original.current)) now.onCommit(kept)
    } else if (previewed.current) {
      now.onPreview?.(null)
    }
    now.onClose()
    if (refocus) now.anchor?.focus()
  }, [])

  /*
   * Unmounted while still open — the sheet closed round it, or its swatch was
   * clicked again — keeps the pick (gotcha 63: a draft is flushed, not lost).
   * `done` is reset on mount for StrictMode's rehearsal unmount, which must not
   * count as a close.
   */
  useEffect(() => {
    done.current = false
    return () => {
      if (done.current) return
      const now = latest.current
      const kept = (now.typed !== null ? parseTyped(now.typed) : null) ?? now.hex
      if (!sameColor(kept, original.current)) {
        done.current = true
        now.onCommit(kept)
      }
    }
  }, [])

  // Live preview, coalesced to one per frame: a drag moves many times a frame.
  useEffect(() => {
    if (!latest.current.onPreview) return
    if (!previewed.current && sameColor(hex, original.current)) return
    const frame = requestAnimationFrame(() => {
      if (done.current) return
      previewed.current = true
      latest.current.onPreview?.(hex)
    })
    return () => cancelAnimationFrame(frame)
  }, [hex])

  /* ------------------------------------------------------------ placement */

  const [pos, setPos] = useState<{ left: number; top: number; side: 'below' | 'above' } | null>(null)
  const place = useCallback((): void => {
    const pop = popRef.current
    const a = latest.current.anchor
    if (!pop || !a) return
    const rem = parseFloat(getComputedStyle(document.documentElement).fontSize) || 16
    const next = placePopover(
      a.getBoundingClientRect(),
      { width: pop.offsetWidth, height: pop.offsetHeight },
      { width: window.innerWidth, height: window.innerHeight },
      GAP_REM * rem,
      EDGE_PX
    )
    setPos((p) => (p && p.left === next.left && p.top === next.top && p.side === next.side ? p : next))
  }, [])

  /*
   * The picker's own size changes as it is used — the ink notes come and go
   * with the pick — and re-placing it then would move the ring and the map
   * under a pointer that is dragging them (measured: opened above its swatch,
   * the ink note vanishing mid-drag slid the whole picker down 38px, and a drag
   * aimed at 75% brightness landed on 100%). So its own
   * resize only keeps it inside the window, top where it was; the swatch
   * moving (a scroll, a window resize) places it afresh.
   */
  const keepInside = useCallback((): void => {
    const pop = popRef.current
    if (!pop) return
    setPos((p) => {
      if (!p) return p
      const top = Math.max(EDGE_PX, Math.min(p.top, window.innerHeight - EDGE_PX - pop.offsetHeight))
      return top === p.top ? p : { ...p, top }
    })
  }, [])

  useLayoutEffect(() => {
    place()
    const pop = popRef.current
    const ro = pop ? new ResizeObserver(keepInside) : null
    if (pop) ro?.observe(pop)
    window.addEventListener('resize', place)
    // Capture: the Settings pane is the scroller, and its scroll does not bubble.
    window.addEventListener('scroll', place, true)
    return () => {
      ro?.disconnect()
      window.removeEventListener('resize', place)
      window.removeEventListener('scroll', place, true)
    }
  }, [place, keepInside])

  /* ------------------------------------------------------ closing outside */

  useEffect(() => {
    const onDown = (e: PointerEvent): void => {
      const t = e.target as Node | null
      if (!t || popRef.current?.contains(t) || latest.current.anchor?.contains(t)) return
      finish(true, false)
    }
    document.addEventListener('pointerdown', onDown, true)
    return () => document.removeEventListener('pointerdown', onDown, true)
  }, [finish])

  /*
   * Open ready for the keyboard: the map is the control most picks start on.
   * Once it is placed, and it is never hidden while unplaced (gotcha 137): the
   * first placement is a layout effect, so the unplaced frame never paints
   * anyway, and a `visibility: hidden` there came back as still-hidden under
   * reduced motion — the global 1ms transition on every property — so focus()
   * did nothing, focus stayed on the swatch, and Escape closed the whole sheet
   * (which then COMMITTED the pick through the unmount flush).
   */
  const focused = useRef(false)
  useEffect(() => {
    if (!pos || focused.current) return
    focused.current = true
    mapRef.current?.focus({ preventScroll: true })
  }, [pos])

  /* ------------------------------------------------------------- pointer */

  const hueFrom = (x: number, y: number): number => {
    const r = ringRef.current!.getBoundingClientRect()
    return hueAt(x, y, r.left + r.width / 2, r.top + r.height / 2)
  }

  const onRingDown = (e: React.PointerEvent<HTMLDivElement>): void => {
    if (e.button !== 0) return
    const ring = ringRef.current
    const hole = holeRef.current
    if (!ring || !hole) return
    const r = ring.getBoundingClientRect()
    const d = Math.hypot(e.clientX - (r.left + r.width / 2), e.clientY - (r.top + r.height / 2))
    // The hole between the ring and the map is neither control.
    if (d < hole.getBoundingClientRect().width / 2 - 1) return
    e.preventDefault()
    ring.focus({ preventScroll: true })
    ring.setPointerCapture(e.pointerId)
    drag.current = 'ring'
    const h = hueFrom(e.clientX, e.clientY)
    setHsv((c) => ({ ...c, h }))
  }

  const onMapDown = (e: React.PointerEvent<HTMLDivElement>): void => {
    if (e.button !== 0) return
    const map = mapRef.current
    if (!map) return
    e.preventDefault()
    map.focus({ preventScroll: true })
    map.setPointerCapture(e.pointerId)
    drag.current = 'map'
    const sv = svAt(e.clientX, e.clientY, map.getBoundingClientRect())
    setHsv((c) => ({ ...c, ...sv }))
  }

  const onMove = (e: React.PointerEvent<HTMLDivElement>): void => {
    if (drag.current === 'ring' && ringRef.current?.hasPointerCapture(e.pointerId)) {
      const h = hueFrom(e.clientX, e.clientY)
      setHsv((c) => ({ ...c, h }))
    } else if (drag.current === 'map' && mapRef.current?.hasPointerCapture(e.pointerId)) {
      const sv = svAt(e.clientX, e.clientY, mapRef.current.getBoundingClientRect())
      setHsv((c) => ({ ...c, ...sv }))
    }
  }

  const endDrag = (): void => {
    drag.current = null
  }

  /* ------------------------------------------------------------ keyboard */

  const onRingKey = (e: React.KeyboardEvent): void => {
    const h = stepHue(hsv.h, e.key, e.shiftKey)
    if (h === null) return
    e.preventDefault()
    e.stopPropagation()
    setHsv((c) => ({ ...c, h }))
  }

  const onMapKey = (e: React.KeyboardEvent): void => {
    const sv = stepSv(hsv, e.key, e.shiftKey)
    if (sv === null) return
    e.preventDefault()
    e.stopPropagation()
    setHsv((c) => ({ ...c, ...sv }))
  }

  /*
   * Escape is the picker's while it is open, wherever focus is: caught on the
   * window in the capture phase, before App's own listener (which would close
   * the whole Settings sheet — and the sheet's unmount would then KEEP the
   * pick, the opposite of what Escape asked for).
   */
  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.key !== 'Escape' || e.defaultPrevented || done.current) return
      e.preventDefault()
      e.stopPropagation()
      finish(false, true)
    }
    window.addEventListener('keydown', onKey, true)
    return () => window.removeEventListener('keydown', onKey, true)
  }, [finish])

  const onRootKey = (e: React.KeyboardEvent): void => {
    if (e.key === 'Enter' && !(e.target instanceof HTMLButtonElement)) {
      e.preventDefault()
      e.stopPropagation()
      finish(true, true)
    }
  }

  /* ------------------------------------------------------------ hex field */

  const onTyped = (text: string): void => {
    setTyped(text)
    setBad(false)
    // Live only once the text is a whole colour: "#e0" on the way to "#e07b2e"
    // is not a colour to repaint to.
    if (typedIsComplete(text)) {
      const p = parseTyped(text)
      if (p) setFromHex(p)
    }
  }

  const settleTyped = (): string | null => {
    if (typed === null) return hex
    const p = parseTyped(typed)
    if (!p) {
      setBad(true)
      return null
    }
    setFromHex(p)
    setTyped(null)
    setBad(false)
    return p
  }

  /* ----------------------------------------------------------- eyedropper */

  const Dropper = useMemo(eyeDropperCtor, [])
  // Claimed before the await, so a second press cannot open a second one (gotcha 20).
  const picking = useRef(false)
  const pickFromScreen = async (): Promise<void> => {
    if (picking.current || !Dropper) return
    picking.current = true
    try {
      const got = await new Dropper().open()
      if (!done.current) setFromHex(got.sRGBHex)
    } catch {
      // Escape, or a click it could not read: nothing picked.
    } finally {
      picking.current = false
    }
  }

  /* ------------------------------------------------------ the ink preview */

  // Read once: the ink is judged against the page this was opened over.
  const theme = useMemo(readRootTheme, [])
  const preview = ((): React.JSX.Element | null => {
    if (!ink) return null
    if (ink.kind === 'agent') {
      const t = agentTokensFor(ink.key, hex, theme.appearance, theme.colors)
      const shift = inkShift(hex, t.text)
      const near = reservedNear(hex, theme, (r) => clearanceFloor(ink.key, r, theme.appearance))
      return (
        <div className="cp-ink">
          <div className="cp-ink-row">
            <span className="cp-ink-label">On this theme</span>
            <span className="cp-tag-sample" style={{ '--cp-ink': t.ink, '--cp-text': t.text } as CSSProperties}>
              {ink.tag}
            </span>
            <span className="cp-ink-hex mono">{t.text}</span>
          </div>
          {shift && (
            <p className="cp-note">
              Stoke paints it {shift.darker ? 'darker' : 'lighter'} here, {t.text}, so the tab tag reads at 4.5:1.
            </p>
          )}
          {near.length > 0 && (
            <p className="cp-note" data-tone="warning">
              Close to {near.map((n) => RESERVED_WORDS[n.name]).join(' and ')} on this theme, so it may be read as that.
            </p>
          )}
        </div>
      )
    }
    if (ink.kind === 'accent') {
      const t = deriveAccent(hex, theme.appearance, theme.colors.bg)
      const shift = inkShift(hex, t.accentInk)
      return (
        <div className="cp-ink">
          <div className="cp-ink-row">
            <span className="cp-ink-label">On this theme</span>
            <span className="cp-text-sample" style={{ '--cp-text': t.accentInk } as CSSProperties}>
              Aa
            </span>
            <span className="cp-fill-sample" style={{ '--cp-fill': t.accent, '--cp-on': t.accentContrast } as CSSProperties}>
              Button
            </span>
          </div>
          {shift && (
            <p className="cp-note">
              Text and outlines use {t.accentInk} here, {shift.darker ? 'darker' : 'lighter'} than the pick, so they read at
              4.5:1.
            </p>
          )}
        </div>
      )
    }
    const p = profileAccentFor(hex)
    if (!p) return null
    const moved = inkShift(hex, p.accent)
    return (
      <div className="cp-ink">
        <div className="cp-ink-row">
          <span className="cp-ink-label">As the chip</span>
          <span className="cp-fill-sample" style={{ '--cp-fill': p.accent, '--cp-on': p.accentContrast } as CSSProperties}>
            {ink.name}
          </span>
          <span className="cp-ink-hex mono">{p.accent}</span>
        </div>
        {moved && (
          <p className="cp-note">
            Kept as {p.accent}, {moved.darker ? 'darker' : 'lighter'} than the pick, so the chip’s label reads at 4.5:1.
          </p>
        )}
      </div>
    )
  })()

  /* --------------------------------------------------------------- render */

  const name = colorName(hsv)
  const pct = (x: number): number => Math.round(x * 100)
  const host = anchor?.closest('[role="dialog"]') ?? document.body

  return createPortal(
    <div
      ref={popRef}
      className="color-picker"
      role="dialog"
      aria-label={`${label}: colour picker`}
      data-side={pos?.side}
      style={{ left: pos?.left ?? 0, top: pos?.top ?? 0 }}
      onKeyDown={onRootKey}
      onBlur={(e) => {
        // Focus leaving to somewhere else keeps the pick, like a click there.
        // A null relatedTarget is the window losing focus, or the eyedropper.
        const to = e.relatedTarget as Node | null
        if (!to || popRef.current?.contains(to) || latest.current.anchor?.contains(to)) return
        finish(true, false)
      }}
    >
      <div className="cp-head">
        <span className="cp-preview" aria-hidden="true">
          <span className="cp-preview-new" style={{ background: hex }} />
          <span className="cp-preview-old" style={{ background: original.current }} />
        </span>
        <input
          className="input mono cp-hex"
          value={typed ?? hex}
          spellCheck={false}
          aria-label={`${label}, hex`}
          aria-invalid={bad || undefined}
          onChange={(e) => onTyped(e.target.value)}
          onBlur={() => void settleTyped()}
          onKeyDown={(e) => {
            if (e.key !== 'Enter') return
            e.preventDefault()
            e.stopPropagation()
            const p = settleTyped()
            if (p) finish(true, true, p)
          }}
        />
        {Dropper && (
          <button
            type="button"
            className="icon-btn"
            data-size="sm"
            title="Pick a colour from the screen"
            onClick={() => void pickFromScreen()}
          >
            <IconEyedropper />
            <span className="sr-only">Pick a colour from the screen</span>
          </button>
        )}
      </div>
      <span className="cp-name">{name}</span>

      <div className="cp-wheel" style={{ '--cp-ring-paint': RING, '--cp-hue': pureHue(hsv.h) } as CSSProperties}>
        <div
          ref={ringRef}
          className="cp-ring"
          role="slider"
          tabIndex={0}
          aria-label="Hue"
          aria-valuemin={0}
          aria-valuemax={359}
          aria-valuenow={Math.round(hsv.h) % 360}
          aria-valuetext={`${Math.round(hsv.h) % 360} degrees, ${hueName(hsv.h)}`}
          onPointerDown={onRingDown}
          onPointerMove={onMove}
          onPointerUp={endDrag}
          onPointerCancel={endDrag}
          onLostPointerCapture={endDrag}
          onKeyDown={onRingKey}
        >
          <span ref={holeRef} className="cp-hole" />
          <span className="cp-ring-handle" style={{ '--cp-angle': `${hsv.h}deg` } as CSSProperties} />
        </div>
        <div
          ref={mapRef}
          className="cp-map"
          role="slider"
          tabIndex={0}
          aria-label="Saturation and brightness"
          aria-valuemin={0}
          aria-valuemax={100}
          aria-valuenow={pct(hsv.s)}
          aria-valuetext={`saturation ${pct(hsv.s)}%, brightness ${pct(hsv.v)}%, ${name}`}
          onPointerDown={onMapDown}
          onPointerMove={onMove}
          onPointerUp={endDrag}
          onPointerCancel={endDrag}
          onLostPointerCapture={endDrag}
          onKeyDown={onMapKey}
        >
          <span
            className="cp-map-handle"
            style={{ left: `${hsv.s * 100}%`, top: `${(1 - hsv.v) * 100}%`, background: hex }}
          />
        </div>
      </div>

      {preview}

      {presets && presets.length > 0 && (
        <div className="cp-presets" role="group" aria-label="Presets">
          {presets.map((p) => (
            <button
              key={`${p.name}-${p.hex}`}
              type="button"
              className="cp-preset"
              title={p.name}
              aria-label={`${p.name}, ${p.hex}`}
              aria-pressed={sameColor(p.hex, hex)}
              style={{ '--cp-swatch': p.hex } as CSSProperties}
              onClick={() => setFromHex(p.hex)}
            />
          ))}
        </div>
      )}

      <div className="cp-actions">
        {defaultValue && !sameColor(defaultValue, hex) && (
          <button
            type="button"
            className="btn"
            data-size="sm"
            data-variant="ghost"
            onClick={() => {
              setFromHex(defaultValue)
              // The button goes once the pick IS the default; focus must not go
              // with it to <body>, where Enter and Escape no longer reach here.
              mapRef.current?.focus({ preventScroll: true })
            }}
          >
            Reset to default
          </button>
        )}
        <span className="cp-spacer" />
        <button type="button" className="btn" data-size="sm" data-variant="ghost" onClick={() => finish(false, true)}>
          Cancel
        </button>
        <button type="button" className="btn" data-size="sm" data-variant="primary" onClick={() => finish(true, true)}>
          Done
        </button>
      </div>
    </div>,
    host
  )
}
