import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync
} from 'node:fs'
import { open, stat } from 'node:fs/promises'
import { homedir, tmpdir } from 'node:os'
import { join } from 'node:path'
import type {
  SessionEvent,
  StatusLinePayload,
  StatusLineRateLimit,
  StatusLineSnapshot,
  StatusLineWindowReading
} from '@shared/types'

/**
 * Stoke's own `statusLine` command, and the payload it captures.
 *
 * The CLI pipes a JSON object to the configured statusLine command on stdin
 * and prints whatever that command writes to stdout. That is the only channel
 * that states the context window before a single token is spent — the
 * transcript never records the tier, and the startup banner stopped saying it
 * in 2.1.221 (see CLAUDE.md gotcha 2). It is also the fresher of the two
 * plan-limit sources, being the account state as the CLI was just told it.
 * It was once the only one that worked on macOS, because `usage.ts` read the
 * token only from ~/.claude/.credentials.json and macOS keeps it in the login
 * Keychain; `readCredentials` reads both now, so the account route answers
 * here too — and it is the one that keeps answering with nothing running.
 *
 * Transport is one file per session under the system temp directory, written
 * temp+rename so a reader never sees half a payload. Not a unix socket: there
 * is no Windows equivalent a shell command can reach as simply. Not an HTTP
 * POST: curl.exe only exists from Windows 10 1803, and a pass-through would
 * have to tee stdin. Not a pure shell wrapper: `more` paginates and re-wraps
 * and `findstr` truncates past ~8KB, and both do it silently.
 *
 * Nothing here writes to the user's own ~/.claude/settings.json. It is read,
 * once, so the line it configures can be passed through.
 */

const WINDOW_MIN = 1_000
const WINDOW_MAX = 10_000_000

export function statusLineDir(): string {
  return join(tmpdir(), 'stoke', 'statusline')
}

/**
 * A session id is normally a uuid we minted, but `--session-id` can be handed
 * anything, so it is reduced to something safely joinable before it ever
 * becomes part of a path.
 */
function key(sessionId: string): string {
  return sessionId.replace(/[^A-Za-z0-9._-]/g, '_')
}

export function statusLinePayloadFile(sessionId: string): string {
  return join(statusLineDir(), `${key(sessionId)}.json`)
}

/**
 * The wrapper, as source. Plain JavaScript rather than TypeScript because it
 * is executed, not built — which is also what lets verify-statusline run the
 * real artefact instead of a copy of its logic.
 *
 * It never parses the payload: the session id arrives on argv, so a malformed
 * frame costs nothing but a skipped write. It never throws, either — a
 * statusLine command that exits non-zero prints its noise into the TUI.
 */
const WRAPPER_JS = `// Generated by Stoke. See src/main/statusLine.ts; edits here are overwritten.
import { execFileSync } from 'node:child_process'
import { appendFileSync, readFileSync, renameSync, statSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// The shim sets this so <electron> runs as plain node for THIS script — but
// with no env override on the execFileSync below, it would inherit straight
// through into the user's own pass-through command too. Deleted before
// anything else runs: any Electron binary the user's status line invokes
// must start as an app, not as node.
delete process.env.ELECTRON_RUN_AS_NODE

const dir = dirname(fileURLToPath(import.meta.url))
// basename() and nothing else: the id is already sanitised on the way in, and
// this makes a hand-edited settings file unable to escape the directory.
const id = basename(String(process.argv[2] || ''))
// 'event' when the CLI ran this as a hook rather than as the status line.
const mode = String(process.argv[3] || '')

let raw = ''
try {
  raw = readFileSync(0, 'utf8')
} catch {
  raw = ''
}

// A hook. The CLI pipes one JSON object per event (Stop, Notification,
// UserPromptSubmit) and Stoke's main process reads them back off this file.
// Appended rather than replaced, because two events can land inside one poll
// interval. Nothing is ever printed: a UserPromptSubmit hook's stdout is added
// to the model's context, and a Stop hook that prints is shown to the user.
if (mode === 'event') {
  if (id && raw.trim().startsWith('{')) {
    try {
      const target = join(dir, id + '.events.jsonl')
      let size = 0
      try {
        size = statSync(target).size
      } catch {}
      const line = raw.trim().replace(/\\r?\\n/g, ' ') + '\\n'
      // A long session emits thousands of these. Past the cap the file is
      // restarted with this one line rather than trimmed, because the reader
      // tracks an offset and a trim would move every offset under it.
      if (size > 262144) writeFileSync(target, line, 'utf8')
      else appendFileSync(target, line, 'utf8')
    } catch {}
  }
  process.exit(0)
}

// Only a JSON object is stored. A CLI that pipes an error message must not be
// able to overwrite the last good reading with it.
if (id && raw.trim().startsWith('{')) {
  try {
    const target = join(dir, id + '.json')
    const tmp = target + '.' + process.pid + '.tmp'
    writeFileSync(tmp, raw, 'utf8')
    renameSync(tmp, target)
  } catch {}
}

// Pass-through: print the user's own status line, fed the same payload. No
// file means the line is suppressed, which is the default.
//
// This string is the user's own statusLine.command, copied out of their own
// ~/.claude/settings.json and written here by Stoke. Claude Code already runs
// that exact string through this exact shell on every render; re-running it is
// what makes "suppression off" restore what they had. The file only exists
// when they switched suppression off themselves.
let cmd = ''
try {
  cmd = readFileSync(join(dir, id + '.cmd'), 'utf8').trim()
} catch {}

if (cmd) {
  try {
    const win = process.platform === 'win32'
    const shell = win ? process.env.COMSPEC || 'cmd.exe' : '/bin/sh'
    process.stdout.write(
      execFileSync(shell, [win ? '/c' : '-c', cmd], {
        // The payload on stdin, never on argv: cmd.exe /c eats & | ^ < >
        // (CLAUDE.md gotcha 13).
        input: raw,
        encoding: 'utf8',
        // The CLI re-renders this line about every 300ms. A command that
        // cannot answer within a couple of frames is not a status line, and
        // printing it late is worse than not printing it. SIGKILL rather than
        // the default SIGTERM, because a script that traps SIGTERM would keep
        // the CLI's render waiting past the timeout it just fired.
        timeout: 2000,
        killSignal: 'SIGKILL',
        // 256KB. A status line is one or two lines; this is ~4000 lines of 64
        // characters. Deliberately the opposite direction to gotcha 13's
        // advice: that is about buffering one large reply we asked an agent
        // for, this is somebody else's command running three times a second,
        // where a low cap is the containment. Over it, node kills the child
        // and throws, and the rule below applies.
        maxBuffer: 262144,
        // stderr discarded, not inherited: an inherited stderr writes into the
        // PTY, which is the one thing this wrapper must never do.
        stdio: ['pipe', 'pipe', 'ignore']
      })
    )
  } catch {}
}
// A non-zero exit, a signal, a timeout and a blown maxBuffer all arrive as a
// throw, and all four print NOTHING. The write is inside the try on purpose,
// so no partial err.stdout is salvaged either: the CLI paints this stdout
// straight into the TUI, so an error message here would appear in the
// terminal looking like Stoke's own output. A status line that failed is
// shown as no status line.
`

function shimName(): string {
  return process.platform === 'win32' ? 'run.cmd' : 'run.sh'
}

/**
 * Write `content` to `target` without a reader ever observing a truncated
 * file: write to a sibling temp name first, then `renameSync` it into place.
 * `mode`, when given, is applied to the temp file before the rename, so the
 * file that appears at `target` already has its final permissions — a
 * rewrite is never briefly non-executable.
 *
 * Both `wrapper.mjs` and the shim live in one directory shared by every Stoke
 * session on the machine, and are rewritten unconditionally on every call
 * (see writeStatusLineWrapper's doc for why). A plain `writeFileSync` opens
 * with O_TRUNC, so a second session's rewrite would zero the file out for an
 * instant on *every* call, not only across an app update — on POSIX that
 * instant is at worst an empty status line for one render, but on Windows a
 * concurrent reader/executor of that same file hits a sharing violation
 * (EBUSY/EACCES) instead. Rename replaces the directory entry atomically, so
 * a concurrent reader sees either the whole old file or the whole new one.
 */
function writeAtomic(target: string, content: string, mode?: number): void {
  const tmp = `${target}.${process.pid}.tmp`
  writeFileSync(tmp, content, 'utf8')
  if (mode !== undefined) chmodSync(tmp, mode)
  renameSync(tmp, target)
}

/**
 * Write the wrapper and the shim that launches it, and return the shim path.
 *
 * The shim exists because the CLI runs a shell command and Stoke has no node
 * of its own: `ELECTRON_RUN_AS_NODE=1 <electron> wrapper.mjs` is the node it
 * has. Both files are rewritten on every call rather than cached, because
 * process.execPath moves when the app updates and a temp sweeper can delete
 * either of them out from under a long-running session — and a shim pointing
 * at a deleted Electron fails as an empty status line, which looks exactly
 * like it working.
 *
 * Never throws — Task 9's caller relies on that. Every step (the directory,
 * both writes) is inside one try/catch; a filesystem that refuses any of them
 * (read-only, out of space, a permissions problem) degrades to the same
 * "empty status line" the rest of this module already falls back to, instead
 * of taking session spawn down with it. The shim path is still returned in
 * that case — nothing exists at it, so the CLI's statusLine command simply
 * fails to run, which the CLI already tolerates silently.
 */
export function writeStatusLineWrapper(): string {
  const dir = statusLineDir()
  const shim = join(dir, shimName())
  try {
    mkdirSync(dir, { recursive: true })

    const wrapper = join(dir, 'wrapper.mjs')
    writeAtomic(wrapper, WRAPPER_JS)

    if (process.platform === 'win32') {
      writeAtomic(
        shim,
        `@echo off\r\nset ELECTRON_RUN_AS_NODE=1\r\n"${process.execPath}" "${wrapper}" %*\r\n`
      )
    } else {
      writeAtomic(
        shim,
        `#!/bin/sh\nELECTRON_RUN_AS_NODE=1 exec "${process.execPath}" "${wrapper}" "$@"\n`,
        0o755
      )
    }
  } catch {
    // See the doc above: degrade to "empty status line", never throw.
  }
  return shim
}

/**
 * The command string that goes into the settings file's statusLine key.
 *
 * Pure — it names the shim without writing it, so the JSON can be built and
 * asserted without touching the disk. Two quoted arguments and no shell
 * metacharacter, which is what keeps CLAUDE.md gotcha 13 out of this: the
 * string lives inside a --settings FILE and never on an argv.
 */
export function statusLineCommand(
  sessionId: string,
  // Passed in rather than read, so a suite on any machine can ask what the
  // other platform gets — the Windows branch below is the one thing here that
  // cannot be exercised where this is developed.
  platform: NodeJS.Platform = process.platform,
  // Likewise: which interpreter the CLI will use decides the syntax, and that
  // is a fact about the target machine rather than about this one.
  hasGitBash: boolean = platform === 'win32' && gitBashPath() !== null
): string {
  return shimCommand(sessionId, '', platform, hasGitBash)
}

/**
 * The same shim, run as a hook. One extra argument tells the wrapper to
 * append the event rather than store a status line — the CLI pipes both the
 * same way, one JSON object on stdin, so one program serves both.
 */
export function hookCommand(
  sessionId: string,
  platform: NodeJS.Platform = process.platform,
  hasGitBash: boolean = platform === 'win32' && gitBashPath() !== null
): string {
  return shimCommand(sessionId, 'event', platform, hasGitBash)
}

/**
 * The paths Claude Code itself searches for Git Bash, in its own order.
 *
 * Transcribed from the 2.1.x bundle's locator rather than invented, because the
 * only question worth answering here is "what will the CLI do", not "where is
 * bash". Its `de()` reads CLAUDE_CODE_GIT_BASH_PATH first (accepting only a
 * bash/sh basename, and falling through with a warning if it does not exist),
 * then these two fixed installs, then `dirname(which('git'))/../../bin/bash.exe`.
 */
const GIT_BASH_FIXED = [
  'C:\\Program Files\\Git\\bin\\bash.exe',
  'C:\\Program Files (x86)\\Git\\bin\\bash.exe'
]

/** What the CLI accepts as an override; anything else falls through. */
const GIT_BASH_NAMES = new Set(['bash.exe', 'sh.exe', 'bash', 'sh'])

/**
 * Where Claude Code will find Git Bash on this machine, or null for none.
 *
 * `env` and `exists` are arguments so a suite on any platform can ask about a
 * Windows machine's layout — the same reason `claudePaths.ts` takes them.
 *
 * This exists because the answer decides the SYNTAX of the statusLine command,
 * and getting it backwards silently disables the status line and all three
 * hooks. See `shimCommand`.
 */
export function gitBashPath(
  env: NodeJS.ProcessEnv = process.env,
  exists: (p: string) => boolean = existsSync
): string | null {
  const override = env.CLAUDE_CODE_GIT_BASH_PATH
  if (override) {
    // basename by hand rather than through `path`, which resolves against the
    // separator of the machine this runs on rather than the one described.
    const base = override.split(/[\\/]/).pop()?.toLowerCase() ?? ''
    if (GIT_BASH_NAMES.has(base) && exists(override)) return override
    // Falls through exactly as the CLI does: a bad override warns and is
    // ignored rather than disabling detection.
  }

  for (const p of GIT_BASH_FIXED) if (exists(p)) return p

  // `which git`, then up two and across — a Git for Windows install has
  // cmd/git.exe beside bin/bash.exe.
  for (const dir of (env.PATH ?? env.Path ?? '').split(';')) {
    if (!dir) continue
    const trimmed = dir.replace(/[\\/]+$/, '')
    if (!exists(`${trimmed}\\git.exe`)) continue
    const up = trimmed.split(/[\\/]/).slice(0, -1).join('\\')
    const candidate = `${up}\\bin\\bash.exe`
    if (exists(candidate)) return candidate
  }

  return null
}

function shimCommand(
  sessionId: string,
  mode: string,
  platform: NodeJS.Platform,
  hasGitBash: boolean
): string {
  const line =
    `"${join(statusLineDir(), shimName())}" "${key(sessionId)}"` + (mode ? ` "${mode}"` : '')
  /*
   * On Windows the syntax depends on which shell the CLI will use, and it uses
   * whichever one it can find.
   *
   * `HD()` in the CLI's own bundle is `cs() ? "bash" : "powershell"`, where
   * `cs()` is "not Windows, or Git Bash was located" — so Git Bash is the
   * PREFERRED interpreter on Windows and PowerShell is the fallback. Stoke
   * sets no `shell` field on either the statusLine or the hook entries, so that
   * default is what governs. The CLI's own help text says as much: "the command
   * is executed through Git Bash".
   *
   * The two shells need opposite things, and there is no single string that
   * satisfies both:
   *
   *   PowerShell parses a line beginning with a quoted string as a string
   *   EXPRESSION rather than an invocation, so `"C:\...\run.cmd" "key"` is a
   *   ParserError — measured against real pwsh 7.6.5, exit 1. The call operator
   *   `&` is what makes it an invocation.
   *
   *   A POSIX shell — which is what Git Bash is — treats a leading `&` as a
   *   syntax error outright. Measured: `bash -c '& echo hi'` gives "syntax
   *   error near unexpected token `&'", and so do sh and zsh.
   *
   * 0.5.4 added the `&` unconditionally for the PowerShell case, under a
   * comment asserting it was "harmless in the Git Bash branch, where `&` is
   * only meaningful when it *ends* a command". That is false, and it inverted
   * the bug: the fix for machines without Git for Windows broke every machine
   * WITH it — which is the CLI's own preferred configuration. On those the shim
   * never ran at all, so no payload was ever written (no context ring, nothing
   * for the plan-limit chip), none of the Stop/Notification/UserPromptSubmit
   * hooks fired (no activity dot, no "Claude is working…", no notifications),
   * and the user's own previously configured statusLine stopped appearing too,
   * because the wrapper that re-runs it as pass-through is what failed to
   * start.
   *
   * So the interpreter is detected rather than assumed, by mirroring the CLI's
   * own locator (`gitBashPath`). Detection can only be wrong in the direction
   * the machine actually is: if Git Bash appears or disappears between here and
   * the session launching, the worst case is the state this code was already in
   * for one of the two populations.
   */
  return platform === 'win32' && !hasGitBash ? `& ${line}` : line
}

function windowSize(v: unknown): number | null {
  if (typeof v !== 'number' || !Number.isFinite(v)) return null
  const n = Math.round(v)
  // Bounded for the same reason windowFromBanner is: a nonsense value large
  // enough to read 0% forever would hide a real overflow.
  return n >= WINDOW_MIN && n <= WINDOW_MAX ? n : null
}

function percent(v: unknown): number | null {
  if (typeof v !== 'number' || !Number.isFinite(v)) return null
  return Math.max(0, Math.min(100, v))
}

function text(v: unknown): string | null {
  return typeof v === 'string' && v.trim() ? v.trim() : null
}

/**
 * `resets_at` is epoch SECONDS in this payload and epoch milliseconds
 * everywhere else in Stoke. This function is the only place the two meet.
 */
function reading(raw: StatusLineRateLimit | undefined): StatusLineWindowReading | null {
  const pct = percent(raw?.used_percentage)
  if (pct === null) return null
  const secs = raw?.resets_at
  const resetsAt =
    typeof secs === 'number' && Number.isFinite(secs) && secs > 0 ? Math.round(secs * 1000) : null
  return { percent: pct, resetsAt }
}

/**
 * The wire payload as the rest of the app wants it: flat, camelCase, and in
 * milliseconds, so no component ever meets the snake_case shape or the
 * seconds/ms boundary.
 *
 * `key` is what the payload file is named after, which is the session id for
 * every session Stoke mints an id for. A `--continue` session's id is chosen
 * by the CLI *after* launch, so its files are named after a launch key
 * instead — and `session_id` in the payload is then the only place the real id
 * appears at all. So the payload's own statement wins, and the key is the
 * fallback. (Contracts §0.2 names this parameter `sessionId`; the name is the
 * only thing that changes, and it changes because it is no longer always one.)
 */
export function toSnapshot(
  key: string,
  payload: StatusLinePayload,
  receivedAt: number
): StatusLineSnapshot {
  const cw = payload.context_window
  return {
    sessionId: text(payload.session_id) ?? key,
    promptId: text(payload.prompt_id),
    contextWindowSize: windowSize(cw?.context_window_size),
    usedPercentage: percent(cw?.used_percentage),
    modelId: text(payload.model?.id),
    modelName: text(payload.model?.display_name),
    exceeds200k: payload.exceeds_200k_tokens === true,
    // Read rather than derived. `probeClaude` answers "what is on disk now",
    // which is a different question from "what is this session running" the
    // moment the CLI updates underneath a session that is still open — and
    // that gap is the entire subject of the relaunch offer.
    cliVersion: text(payload.version),
    fiveHour: reading(payload.rate_limits?.five_hour),
    sevenDay: reading(payload.rate_limits?.seven_day),
    receivedAt
  }
}

/**
 * The last payload this session's wrapper wrote, or null.
 *
 * Null covers every failure the same way on purpose — no file yet, a CLI too
 * old to run a statusLine command, a half-written file, a temp sweeper that
 * deleted it. Every caller has a fallback, and a throw here would take the
 * context meter down with it.
 */
export function readStatusLine(sessionId: string): StatusLineSnapshot | null {
  if (!sessionId) return null
  try {
    const file = statusLinePayloadFile(sessionId)
    const raw = readFileSync(file, 'utf8')
    const at = statSync(file).mtimeMs
    const payload = JSON.parse(raw) as unknown
    if (!payload || typeof payload !== 'object') return null
    return toSnapshot(sessionId, payload as StatusLinePayload, at)
  } catch {
    return null
  }
}

/** Where the pass-through command lives, when there is one. */
function passthroughFile(sessionId: string): string {
  return join(statusLineDir(), `${key(sessionId)}.cmd`)
}

/** Where the hook events land: one JSON object per line, appended. */
export function sessionEventsFile(sessionId: string): string {
  return join(statusLineDir(), `${key(sessionId)}.events.jsonl`)
}

/**
 * The hook events the CLI has written since `offset`, and the offset to read
 * from next time.
 *
 * The wrapper appends one line per event and restarts the file past a size
 * cap, which is the one case an offset can point past the end: the reader
 * then starts over from zero rather than waiting for a file that will never
 * grow back to where it was. A line that is not JSON is skipped, never a
 * throw — this runs on a timer in the main process.
 *
 * Async, and deliberately so: a sync read on a poll is how gotcha 40's boot
 * stall happened. The temp directory is on the internal disk, so this is
 * defence rather than a measured need.
 */
export async function readSessionEvents(
  sessionId: string,
  offset: number
): Promise<{ events: SessionEvent[]; offset: number }> {
  const file = sessionEventsFile(sessionId)
  let size: number
  try {
    size = (await stat(file)).size
  } catch {
    return { events: [], offset: 0 }
  }
  const from = offset > size ? 0 : offset
  if (size === from) return { events: [], offset: from }
  let text: string
  try {
    const handle = await open(file, 'r')
    try {
      const buf = Buffer.alloc(size - from)
      await handle.read(buf, 0, buf.length, from)
      text = buf.toString('utf8')
    } finally {
      await handle.close()
    }
  } catch {
    return { events: [], offset: from }
  }
  // Only whole lines. A line still being appended is left for the next read.
  const lastNewline = text.lastIndexOf('\n')
  if (lastNewline < 0) return { events: [], offset: from }
  const whole = text.slice(0, lastNewline + 1)
  const events: SessionEvent[] = []
  for (const line of whole.split('\n')) {
    const ev = parseHookEvent(line, sessionId)
    if (ev) events.push(ev)
  }
  return { events, offset: from + Buffer.byteLength(whole, 'utf8') }
}

/**
 * One hook line as the renderer wants it. Exported so the suite can hand it
 * the exact payloads captured from a real CLI.
 *
 * The three events Stoke subscribes to are the three that describe where a
 * session is: a prompt was submitted (working), the assistant stopped (done,
 * waiting for you), or the CLI asked for attention (a permission prompt, or
 * an idle nudge). `session_id` in the payload wins over the key for the same
 * reason it does in `toSnapshot`: a `--continue` session's file is named after
 * a launch key, and only the payload knows the real id.
 */
export function parseHookEvent(line: string, key: string): SessionEvent | null {
  const trimmed = line.trim()
  if (!trimmed.startsWith('{')) return null
  let raw: Record<string, unknown>
  try {
    raw = JSON.parse(trimmed) as Record<string, unknown>
  } catch {
    return null
  }
  const name = text(raw.hook_event_name)
  const kind: SessionEvent['kind'] | null =
    name === 'Stop'
      ? 'stop'
      : name === 'Notification'
        ? 'notification'
        : name === 'UserPromptSubmit'
          ? 'prompt'
          : null
  if (!kind) return null
  const message =
    kind === 'stop'
      ? text(raw.last_assistant_message)
      : kind === 'notification'
        ? text(raw.message)
        : text(raw.prompt)
  return {
    sessionId: text(raw.session_id) ?? key,
    kind,
    at: Date.now(),
    // Bounded: a Stop carries the whole last reply, which can be pages.
    message: message ? message.slice(0, 400) : null,
    notificationType: kind === 'notification' ? text(raw.notification_type) : null,
    cwd: text(raw.cwd)
  }
}

function settingsFileFor(sessionId: string): string {
  return join(statusLineDir(), `${key(sessionId) || 'default'}.settings.json`)
}

export interface SessionSettingsInput {
  /**
   * The statusLine KEY this session's three files are named after — not
   * necessarily a session id. It is the session id for everything Stoke mints
   * an id for, and a launch key for a `--continue`, whose id the CLI chooses
   * after launch. See pty.ts, which is the only caller.
   */
  sessionId: string
  ultracode: boolean
  hideStatusLine: boolean
  /** The user's own statusLine command, or '' when there is nothing to echo. */
  passthroughCommand: string
}

/**
 * Everything Stoke puts in one session's `--settings` file.
 *
 * One file, because a second `--settings` silently discards the first —
 * measured against 2.1.221, and the reason this function exists at all rather
 * than each feature appending its own flag.
 *
 * Every session with a key gets the statusLine entry, including a `--continue`
 * — pty.ts gives that one a launch key precisely so it does. Without it, the
 * setting "Hide Claude's status line in Stoke" would silently not apply to the
 * one launch path whose id we do not know in advance.
 *
 * No key at all still means no statusLine entry: there would be nothing to
 * name the payload, the pass-through file or the settings file after.
 */
export function sessionSettingsJson(input: SessionSettingsInput): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  if (input.ultracode) out.ultracode = true
  if (input.sessionId) {
    out.statusLine = { type: 'command', command: statusLineCommand(input.sessionId) }
    /*
     * The hooks that tell Stoke where a session is. Measured against 2.1.237:
     * hooks in a `--settings` file fire, and they MERGE with the user's own
     * (a project-level UserPromptSubmit hook and this one both ran on the
     * same prompt), so this adds to whatever the user has rather than
     * replacing it. Every entry has no matcher, so it applies to every
     * event of that name, and the command prints nothing — a Stop hook that
     * prints is shown in the TUI, and a UserPromptSubmit hook's stdout goes
     * into the model's context. `timeout` is seconds; the wrapper takes
     * milliseconds, so 10 is a ceiling nothing should reach.
     */
    const hook = [{ hooks: [{ type: 'command', command: hookCommand(input.sessionId), timeout: 10 }] }]
    out.hooks = { Stop: hook, Notification: hook, UserPromptSubmit: hook }
  }
  return out
}

/**
 * Write that file and the pass-through command beside it, and return the path
 * for `--settings`. Null means there is nothing to pass.
 *
 * A failure returns null rather than throwing: buildArgs falls back to the
 * ultracode-only file, which does throw if it cannot be written, so the one
 * case that must stay loud — a session that promised ultracode and did not
 * get it — still is.
 */
export function writeSessionSettingsFile(input: SessionSettingsInput): string | null {
  const json = sessionSettingsJson(input)
  if (!Object.keys(json).length) return null
  try {
    mkdirSync(statusLineDir(), { recursive: true })
    if (json.statusLine) writeStatusLineWrapper()
    if (input.sessionId) {
      const cmdFile = passthroughFile(input.sessionId)
      const passthrough = input.hideStatusLine ? '' : input.passthroughCommand.trim()
      // Removed rather than left in place when suppression is on: a stale
      // file would keep printing a line the user has just turned off.
      //
      // The write is atomic (temp + rename), not a plain writeFileSync: the
      // wrapper polls this exact file roughly every 300ms (see WRAPPER_JS
      // above), so an in-place O_TRUNC rewrite is a window where a read lands
      // on an empty or truncated command — and a truncation that still
      // happens to parse as shell would run something other than what the
      // user configured, not just nothing.
      if (passthrough) writeAtomic(cmdFile, passthrough)
      else rmSync(cmdFile, { force: true })
    }
    const file = settingsFileFor(input.sessionId)
    writeAtomic(file, `${JSON.stringify(json, null, 2)}\n`)
    return file
  } catch (err) {
    console.error('[stoke] could not write the session settings file', err)
    return null
  }
}

/** Remove everything written for one session. Called when its PTY exits. */
export function clearSessionFiles(sessionId: string): void {
  if (!sessionId) return
  for (const f of [
    statusLinePayloadFile(sessionId),
    passthroughFile(sessionId),
    settingsFileFor(sessionId),
    sessionEventsFile(sessionId)
  ]) {
    try {
      rmSync(f, { force: true })
    } catch {
      /* a temp sweeper got there first */
    }
  }
}

/**
 * How stale a per-session file must be before the boot sweep below will
 * remove it.
 *
 * Six hours: comfortably longer than any coding session Stoke is likely to
 * hold open in one sitting, and nowhere near the sub-second cadence the
 * wrapper renders on (WRAPPER_JS is re-run roughly three times a second by
 * the CLI), so it cannot mistake a live session's own render gap for death.
 * The failure mode on either side is asymmetric: too low risks deleting a
 * slow-but-live session's files (rare, and only on the '.settings.json'/
 * '.cmd' side — see the "protected keys" comment below for why that is
 * actually contained); too high just means a dead session's few-KB files sit
 * around longer, which is the entire status quo this sweep is fixing, only
 * bounded now instead of unbounded.
 */
const STALE_AFTER_MS = 6 * 60 * 60 * 1000

/** Shared infrastructure the sweep must never remove: `writeStatusLineWrapper` rewrites both unconditionally on every launch anyway, so deleting them only costs the next session a redundant write. */
const NEVER_SWEEP = new Set(['wrapper.mjs', 'run.sh', 'run.cmd'])

/**
 * Split one directory entry into the key its session files share and which
 * of the three kinds this particular file is. `.settings.json` is checked
 * before the plainer `.json` suffix on purpose - the shorter suffix would
 * otherwise match first and leave `.settings` glued onto the key.
 */
function fileKeyAndKind(name: string): { fileKey: string; kind: 'payload' | 'settings' | 'cmd' | 'events' | 'other' } {
  if (name.endsWith('.settings.json')) {
    return { fileKey: name.slice(0, -'.settings.json'.length), kind: 'settings' }
  }
  if (name.endsWith('.events.jsonl')) {
    return { fileKey: name.slice(0, -'.events.jsonl'.length), kind: 'events' }
  }
  if (name.endsWith('.json')) return { fileKey: name.slice(0, -'.json'.length), kind: 'payload' }
  if (name.endsWith('.cmd')) return { fileKey: name.slice(0, -'.cmd'.length), kind: 'cmd' }
  return { fileKey: name, kind: 'other' }
}

/**
 * Remove per-session statusLine files that nothing else will ever clean up:
 * a crash, a SIGKILL, or a launch that failed before its exit handler could
 * be registered all skip `clearSessionFiles` entirely, and it has no other
 * caller anywhere in the app besides pty.ts and the verify suite - so
 * without this, three ordinary ways to end a session (see pty.ts's callers)
 * leave a `.settings.json`/`.cmd`/`.json` triple behind forever. Each
 * `.json` holds that session's token counts and plan-usage percentages, so
 * this is not just tidiness.
 *
 * Meant to run once, at boot, before any session is started.
 *
 * `statusLineDir()` is one directory shared by every Stoke install on the
 * machine - an unpackaged dev run gets its own userData so it never fights
 * an installed copy for the single-instance lock, but both write into the
 * SAME tmpdir. A blanket wipe here would delete the live session files of
 * an already-running installed Stoke the moment a dev build boots, breaking
 * its status line mid-session. So this only ever removes a file whose own
 * mtime is older than `STALE_AFTER_MS` - old enough that no plausible live
 * session, from either install, could have produced it.
 *
 * That age test is sound for a `.json` payload on its own: the wrapper
 * rewrites it on every render (WRAPPER_JS above), so a live session's
 * payload mtime never falls behind by more than a render gap. It is NOT
 * sound on its own for `.settings.json` or `.cmd` - both are written once at
 * launch and never touched again, so their mtime is the session's *start*
 * time. Applying the threshold to them unmodified would eventually reap a
 * long-running session's own settings out from under it. So a
 * `.settings.json`/`.cmd` is protected whenever its sibling `<key>.json`
 * payload is itself fresh - which is exactly the signal that the session
 * that owns that key is still alive and still rendering.
 *
 * Never throws: every filesystem call is individually guarded, matching
 * `writeStatusLineWrapper`'s contract, because a sweep that took the app's
 * boot down with it would be strictly worse than the leak it exists to fix.
 */
export function sweepStaleSessionFiles(now: number = Date.now()): void {
  const dir = statusLineDir()
  let names: string[]
  try {
    names = readdirSync(dir)
  } catch {
    return // nothing written yet on this machine - nothing to sweep
  }

  // Pass 1: which keys have a fresh payload right now. Read before anything
  // is removed, so pass 2's protection check never races its own deletions.
  const freshPayloadKeys = new Set<string>()
  for (const name of names) {
    if (NEVER_SWEEP.has(name)) continue
    const { fileKey, kind } = fileKeyAndKind(name)
    if (kind !== 'payload') continue
    try {
      const age = now - statSync(join(dir, name)).mtimeMs
      if (age <= STALE_AFTER_MS) freshPayloadKeys.add(fileKey)
    } catch {
      /* raced with something else removing it; irrelevant either way */
    }
  }

  for (const name of names) {
    if (NEVER_SWEEP.has(name)) continue
    const { fileKey, kind } = fileKeyAndKind(name)
    // An events file is appended on every turn and idle between them, so its
    // mtime says "last event" rather than "still alive" — protected while the
    // payload beside it is fresh, exactly like the settings and cmd files.
    if ((kind === 'settings' || kind === 'cmd' || kind === 'events') && freshPayloadKeys.has(fileKey)) continue
    try {
      const full = join(dir, name)
      const age = now - statSync(full).mtimeMs
      if (age > STALE_AFTER_MS) rmSync(full, { force: true })
    } catch {
      /* already gone, or a live process is touching it right now - either way, leave it */
    }
  }
}

/**
 * The context window for a session, in order of authority.
 *
 * 1. The statusLine payload. A direct statement, per model, correct from token
 *    zero, and the only one that still exists — claude 2.1.221 dropped
 *    "(1M context)" from its startup banner.
 * 2. The banner, for a CLI old enough to still print it.
 * 3. Null, and `contextLimitFor` falls back to inferring the tier from observed
 *    usage. That cannot be right below 200k, but it is never wrong in the
 *    dangerous direction.
 *
 * A named function rather than a lambda inside the ContextWatcher construction
 * because this ordering is the whole point of the statusLine channel, and a
 * lambda in a constructor call is the one shape no suite here can reach.
 *
 * `sessionId` is safe to use as the payload key here, though the two are not
 * the same thing in general. This is only ever called from the context
 * watcher, and there are exactly three kinds of session it watches:
 *
 *  - a local session Stoke minted an id for, whose statusLine key IS that id;
 *  - a remote session, which has no key and no payload at all — its `claude`
 *    runs on the far machine — so this falls through to the banner for it,
 *    exactly as it did before the payload existed;
 *  - and not a `--continue`, whose files are named after a launch key: it is
 *    never watched, because context.ts:99 no-ops on the empty id it has.
 *
 * So no caller can reach here holding a key that names somebody else's file.
 */
export function windowFor(sessionId: string, bannerWindow: number | null): number | null {
  return readStatusLine(sessionId)?.contextWindowSize ?? bannerWindow ?? null
}

/**
 * The user's own statusLine command, so it can be passed through when the
 * line is not suppressed. Read at launch rather than cached, because the file
 * is theirs and they can change it at any time.
 *
 * Read-only, always: Stoke never writes to Claude Code's own files.
 */
export function userStatusLineCommand(
  settingsFile: string = join(homedir(), '.claude', 'settings.json')
): string {
  try {
    // A leading BOM makes JSON.parse throw. PowerShell 5.1's
    // `Set-Content -Encoding utf8` writes one (CLAUDE.md gotcha 8), and a
    // user hitting that on their own ~/.claude/settings.json would otherwise
    // silently lose their status line here with no diagnostic. Stripped
    // before parsing, never written back — this function still only reads.
    const raw = JSON.parse(readFileSync(settingsFile, 'utf8').replace(/^﻿/, '')) as {
      statusLine?: { type?: string; command?: string }
    }
    const sl = raw?.statusLine
    if (!sl || sl.type !== 'command') return ''
    return typeof sl.command === 'string' ? sl.command.trim() : ''
  } catch {
    return ''
  }
}
