#!/bin/sh
# Stoke, in one line:
#
#     curl -fsSL https://stoke.vinn.dev | sh
#
# Installs or upgrades Stoke on macOS and Linux. Windows is install.ps1; this
# script detects a Windows shell and says so rather than half-working.
#
# It downloads only from github.com/realvinn/stoke/releases and verifies every
# byte against the sha512 in that release's own update manifest before anything
# is installed. STOKE_DRY_RUN=1 does all of that and stops before touching a
# single file outside its temp directory, which is how it is tested.
#
# ---------------------------------------------------------------------------
# Everything is inside main(), which is called on the LAST line, and that is
# structural rather than tidy. `sh` reads its stdin incrementally and executes
# as it reads, so a connection that drops at 60% of a piped script executes the
# first 60% — half an installer is worse than none. A truncated download of this
# file either dies on an unterminated compound command or simply never reaches
# `main "$@"`. Neither one partially installs.
#
# The campfire art block below sits outside main() because it is generated
# verbatim from src/shared/campfire.ts and may not be reindented. It is inert:
# shell variable assignments, nothing executed, nothing reached until main runs.
#
# Debugging flags, all offline and all safe to run:
#     sh install.sh --help
#     sh install.sh --print-plan [tty|pipe]   what the fire would do here
#     sh install.sh --fire-frames <tier>      the twelve frames, painted
#     sh install.sh --sha512 <file>           the manifest's own digest form
# ---------------------------------------------------------------------------
set -eu

# zsh does not split an unquoted parameter expansion on IFS unless it is asked
# to, and three things here depend on that splitting: the flicker table built
# below, the stage thresholds in `fire_stage_of`, and the painter's KEY:text
# segments. Without this line `for fire_v in $FIRE_FLICKER` saw ONE word, so
# `eval "FIRE_FLICK_0=0 1 2 1 0 2"` ran `1` as a command and the script died on
# `command not found: 1` before it had done anything at all — under the shell
# macOS makes the default, which is exactly where somebody types
# `zsh install.sh` after reading it. `zsh -n` parses the file perfectly, which
# is why a suite that only parsed could not see it; verify:install RUNS every
# offline flag under all four shells now.
#
# `setopt sh_word_split` and nothing wider: `emulate sh` would also reset the
# shell options to sh's defaults and take the `set -eu` above with it.
if [ -n "${ZSH_VERSION:-}" ]; then setopt sh_word_split 2>/dev/null || true; fi

STOKE_RELEASES='https://github.com/realvinn/stoke/releases'
STOKE_LATEST_DL="$STOKE_RELEASES/latest/download"
STOKE_PS1_LINE='irm https://stoke.vinn.dev | iex'

# BEGIN CAMPFIRE ART
# Generated by `node scripts/gen-installer-art.mts sh` from src/shared/campfire.ts.
# DO NOT EDIT BY HAND: verify:campfire asserts this block byte for byte against
# the generator, and a hand-encoded row has already shipped a visible `||` once.
#
# Canvas is a fixed 7 rows x 15 columns for every frame, because redraw in
# place is ESC[7A and nothing else -- a shorter frame walks the cursor up the
# screen a row per tick. Flame rows are stored right-trimmed; emit ESC[K per row
# rather than padding to the full width.
#
# 12 frames: 4 stages (spark kindling burning roaring) x 3 flicker frames.
# Pick with: stage from FIRE_STAGE_PCT against the percentage downloaded,
# flicker from FIRE_FLICKER[tick % 6], then n = stage * 3 + flicker and
#   eval "rows=\$FIRE_F$n"    (or FIRE_M$n for the monochrome tier).
#
# Rows are segment-encoded as KEY:text|KEY:text, joined by newlines. Keys:
#   _ uncoloured (spaces)   C core (white-hot)   S spark   M mid   B base   L log
# Neither | nor : can appear in the art, so the split is unambiguous.
# FIRE_M* is the same art with no colour at all, for the monochrome tier.
#
# Print these with a literal format string -- printf '%s' "$row", never
# printf "$row" -- the art is full of backslashes and % is not escaped here.
FIRE_ROWS=7
FIRE_COLS=15
FIRE_MS=125
FIRE_FLICKER='0 1 2 1 0 2'
FIRE_STAGE_PCT='8 35 75'
FIRE_F0='


_:       |S:.
_:      |B:(|C:*|B:)'
FIRE_F1='


_:         |S:^
_:      |B:(|S:,|B:)'
FIRE_F2='


_:     |S:,
_:      |B:(|S:.|B:)'
FIRE_F3='

_:       |S:.
_:      |M:(|_: |M:)
_:     |B:(|C:###|B:)'
FIRE_F4='

_:        |S:^
_:      |M:)|_: |M:(
_:     |B:(|C:#|B:=|C:#|B:)'
FIRE_F5='

_:      |S:,
_:      |M:(|_: |M:)
_:     |B:(|C:#*#|B:)'
FIRE_F6='
_:      |S:.|_: |S:^
_:     |M:)|_: |M:(|_: |M:)
_:    |M:(|_: |M:(|C:#|M:)|_: |M:)
_:   |B:(|_: |B:(|C:###|B:)|_: |B:)'
FIRE_F7='
_:     |S:^|_:  |S:.
_:     |M:(|_: |M:)|_: |M:(
_:    |M:)|_: |M:(|C:#|M:)|_: |M:(
_:   |B:(|_: |B:(|C:###|B:)|_: |B:)'
FIRE_F8='
_:       |C:*|_: |S:.
_:     |M:(|_: |M:)|_: |M:)
_:    |M:(|_: |M:(|C:#|M:)|_: |M:)
_:   |B:(_(|C:###|B:)_)'
FIRE_F9='_:   |S:.|_:   |C:*|_:   |S:.
_:    |S:\|_: |S:)|_: |S:(|_: |S:/
_:   |M:(|_: |M:)(|C:#|M:)(|_: |M:)
_:  |M:(|_: |M:((|C:###|M:))|_: |M:)
_: |B:(_((|C:#####|B:))_)'
FIRE_F10='_:  |C:*|_:   |S:.|_:    |S:^
_:   |S:(|_: |S:\|_: |S:)|_: |S:(/)
_:  |M:(|_: |M:)(|_: |C:#|_: |M:)(|_: |M:)
_:  |M:(|_: |M:((|C:###|M:))|_: |M:)
_: |B:(_((|C:#####|B:))_)'
FIRE_F11='_:   |S:^|_:  |S:.|_:  |C:*|_:  |S:.
_:    |S:)|_: |S:(|_: |S:\|_: |S:/
_:   |M:(|_: |M:)(|C:#|M:)(|_: |M:)
_:  |M:(|_: |M:((|C:###|M:))|_: |M:)
_: |B:(_((|C:#####|B:))_)'
FIRE_FH='L:\__/\_/_\_/\__/
L:.-.,_______,.-.'
FIRE_M0='


       .
      (*)'
FIRE_M1='


         ^
      (,)'
FIRE_M2='


     ,
      (.)'
FIRE_M3='

       .
      ( )
     (###)'
FIRE_M4='

        ^
      ) (
     (#=#)'
FIRE_M5='

      ,
      ( )
     (#*#)'
FIRE_M6='
      . ^
     ) ( )
    ( (#) )
   ( (###) )'
FIRE_M7='
     ^  .
     ( ) (
    ) (#) (
   ( (###) )'
FIRE_M8='
       * .
     ( ) )
    ( (#) )
   (_(###)_)'
FIRE_M9='   .   *   .
    \ ) ( /
   ( )(#)( )
  ( ((###)) )
 (_((#####))_)'
FIRE_M10='  *   .    ^
   ( \ ) (/)
  ( )( # )( )
  ( ((###)) )
 (_((#####))_)'
FIRE_M11='   ^  .  *  .
    ) ( \ /
   ( )(#)( )
  ( ((###)) )
 (_((#####))_)'
FIRE_MH='\__/\_/_\_/\__/
.-.,_______,.-.'
# The palette, as the bytes AFTER ESC. ESC itself comes from `printf '\033'`
# -- octal, because \e is a bash/zsh extension that dash and busybox ash lack.
SGR_TC_C='[38;2;255;243;226m'
SGR_TC_S='[38;2;255;196;140m'
SGR_TC_M='[38;2;255;149;82m'
SGR_TC_B='[38;2;232;95;36m'
SGR_TC_L='[38;2;124;58;29m'
SGR_X2_C='[38;5;230m'
SGR_X2_S='[38;5;216m'
SGR_X2_M='[38;5;209m'
SGR_X2_B='[38;5;166m'
SGR_X2_L='[38;5;94m'
SGR_A1_C='[1;37m'
SGR_A1_S='[1;33m'
SGR_A1_M='[0;33m'
SGR_A1_B='[1;31m'
SGR_A1_L='[0;31m'
SGR_RESET='[0m'
# END CAMPFIRE ART

# How many flicker frames each stage has, so `n = stage * FIRE_STRIDE + flicker`
# addresses the right one of the twelve. The art block states the formula in its
# preamble but carries no variable for the stride, so this is the one number in
# the fire that is hand-written — and `verify:install` asserts it against
# campfire.ts's own stage shape, because a wrong stride is not a crash, it is a
# fire that flickers between the wrong two stages and looks almost right.
FIRE_STRIDE=3

ESC=$(printf '\033')
NL='
'

# The flicker order, as indexable variables. A POSIX shell has no arrays, and
# `set --` would clobber the positional parameters the caller is standing on.
FIRE_FLICK_N=0
for fire_v in $FIRE_FLICKER; do
  eval "FIRE_FLICK_$FIRE_FLICK_N=$fire_v"
  FIRE_FLICK_N=$((FIRE_FLICK_N + 1))
done

# --- talking -------------------------------------------------------------

say() { printf '%s\n' "$*"; }
blank() { printf '\n'; }

# A two-column line, so the transcript of an install reads as a table.
note() { printf '  %-11s %s\n' "$1" "$2"; }

die() {
  fire_cleanup
  blank >&2
  printf '  %s\n' "$@" >&2
  blank >&2
  exit 1
}

usage() {
  cat <<'USAGE'
stoke installer

  curl -fsSL https://stoke.vinn.dev | sh

  STOKE_DRY_RUN=1     resolve, download and verify, then stop. Installs nothing.
  STOKE_FORCE=1       install even when the installed copy is the same or newer.
  STOKE_NO_ANIMATION=1  no fire; one honest line per decile instead.
  NO_COLOR=1          the fire, in one colour. (It still burns: NO_COLOR is
                      about colour, not about motion.)

  --help              this.
  --print-plan [tty|pipe]  what the fire would do in this environment.
  --fire-frames TIER  the twelve frames as they would be painted.
                      TIER is truecolor, ansi256, ansi16 or none.
  --sha512 FILE       a file's sha512 in the base64 form the release manifests
                      use, so a download can be checked against one by hand.

The scripts are readable before you run them:
  https://stoke.vinn.dev/install.sh   https://stoke.vinn.dev/install.ps1
USAGE
}

# --- the fire ------------------------------------------------------------

# Set once by fire_plan, read everywhere.
FIRE_ANIMATE=0
FIRE_COLOR=none   # the tier's NAME, as src/shared/campfire.ts spells it
FIRE_TIER=none    # the same tier as the SGR_* variables spell it: TC, X2, A1
FIRE_WHY=''
FIRE_TICK=0
FIRE_OPEN=0
FIRE_SLEEP=1

# The terminal's size, or empty when nothing will say. Unknown is deliberately
# not a reason to degrade — plenty of perfectly capable terminals answer
# neither, and refusing to draw on one of those is worse than drawing on a
# window that turns out to be small.
term_lines() {
  if [ -n "${LINES:-}" ]; then printf '%s' "$LINES"; return 0; fi
  if command -v tput >/dev/null 2>&1; then tput lines 2>/dev/null || true; fi
}
term_cols() {
  if [ -n "${COLUMNS:-}" ]; then printf '%s' "$COLUMNS"; return 0; fi
  if command -v tput >/dev/null 2>&1; then tput cols 2>/dev/null || true; fi
}

# Whether to animate and in which colour tier. This is a transcription of
# `degradedReason` + `colorMode` in src/shared/campfire.ts, and verify:install
# runs both against each other over a table of environments — the module is the
# definition and this is a copy of it, so the copy is checked rather than
# trusted.
#
# $1 is "tty" or "pipe": passed in rather than measured, exactly as the module
# takes `Terminal.isTty` as an argument, so a suite can ask what this script
# would do on a terminal it does not have.
fire_plan() {
  FIRE_WHY=''
  if [ -n "${STOKE_NO_ANIMATION:-}" ]; then
    FIRE_WHY='STOKE_NO_ANIMATION is set'
  elif [ "$1" != tty ]; then
    FIRE_WHY='stdout is not a terminal'
  elif [ "${TERM:-}" = dumb ]; then
    FIRE_WHY='TERM is dumb'
  elif [ -z "${TERM:-}" ]; then
    FIRE_WHY='TERM is unset'
  elif [ -n "${CI:-}${GITHUB_ACTIONS:-}${TF_BUILD:-}" ]; then
    FIRE_WHY='this is CI'
  else
    fire_l=$(term_lines)
    fire_c=$(term_cols)
    case $fire_l in
      '' | *[!0-9]*) : ;;
      *) if [ "$fire_l" -lt 12 ]; then FIRE_WHY='the window is under 12 rows'; fi ;;
    esac
    if [ -z "$FIRE_WHY" ]; then
      case $fire_c in
        '' | *[!0-9]*) : ;;
        *) if [ "$fire_c" -lt 20 ]; then FIRE_WHY='the window is under 20 columns'; fi ;;
      esac
    fi
  fi

  if [ -n "$FIRE_WHY" ]; then
    # A degraded terminal gets no colour TIER either, not merely no animation:
    # `none` here is what keeps a piped or CI run free of escape bytes.
    FIRE_ANIMATE=0
    fire_set_tier none
    return 0
  fi
  FIRE_ANIMATE=1
  if [ -n "${NO_COLOR:-}" ]; then
    # no-color.org: the variable, "when present and not an empty string", stops
    # ANSI colour. It says nothing whatever about motion, and the art is a
    # silhouette that reads perfectly in one colour. So the fire still burns.
    fire_set_tier none
    return 0
  fi
  if [ -n "${WT_SESSION:-}" ]; then fire_set_tier truecolor; return 0; fi
  fire_ct=$(printf '%s' "${COLORTERM:-}" | tr '[:upper:]' '[:lower:]')
  case $fire_ct in
    *truecolor* | *24bit*) fire_set_tier truecolor; return 0 ;;
  esac
  case ${TERM:-} in
    *256color*) fire_set_tier ansi256; return 0 ;;
  esac
  fire_set_tier ansi16
}

# One tier name in, both spellings out.
fire_set_tier() {
  FIRE_COLOR=$1
  case $1 in
    truecolor) FIRE_TIER=TC ;;
    ansi256) FIRE_TIER=X2 ;;
    ansi16) FIRE_TIER=A1 ;;
    *) FIRE_COLOR=none; FIRE_TIER=none ;;
  esac
}

# One segment-encoded row -> FIRE_ROW, coloured for the current tier.
#
# The encoding is `KEY:text|KEY:text`; neither delimiter can appear in the art,
# which is what makes this split unambiguous. The whole point of the art being
# pre-segmented by the generator is that this loop forks NOTHING: per-glyph
# colour otherwise means an awk or a sed per frame, eight times a second, beside
# a download.
#
# `set -f` is not optional. The art contains `*`, and an unquoted expansion of
# a row with globbing on would try to match filenames with it.
fire_paint_row() {
  FIRE_ROW=''
  fire_active=''
  fire_oifs=$IFS
  IFS='|'
  set -f
  for fire_seg in $1; do
    fire_k=${fire_seg%%:*}
    fire_t=${fire_seg#*:}
    if [ "$fire_k" != _ ]; then
      eval "fire_sgr=\$SGR_${FIRE_TIER}_$fire_k"
      # A sequence equal to the one already in effect is skipped, and a run of
      # spaces emits none and does not end the one in effect — only the
      # foreground is ever set, so that is safe and it is worth 19 bytes a time
      # at truecolor. This mirrors `paint()` in campfire.ts byte for byte, which
      # is what verify:install compares against.
      if [ "$fire_sgr" != "$fire_active" ]; then
        FIRE_ROW=$FIRE_ROW$ESC$fire_sgr
        fire_active=$fire_sgr
      fi
    fi
    FIRE_ROW=$FIRE_ROW$fire_t
  done
  set +f
  IFS=$fire_oifs
  # Every painted row ends with a reset. Not optional: a live foreground across
  # the newline would colour whatever the installer prints next.
  if [ -n "$fire_active" ]; then FIRE_ROW=$FIRE_ROW$ESC$SGR_RESET; fi
}

# Frame $1 (0..11) -> FIRE_FRAME: seven rows joined by newlines, coloured, with
# no cursor movement and no erase-in-line in it. The caller owns the redraw.
fire_frame_text() {
  if [ "$FIRE_TIER" = none ]; then
    eval "fire_body=\$FIRE_M$1"
    FIRE_FRAME=$fire_body$NL$FIRE_MH
    return 0
  fi
  eval "fire_body=\$FIRE_F$1"
  fire_body=$fire_body$NL$FIRE_FH
  FIRE_FRAME=''
  fire_rest=$fire_body
  fire_i=0
  # Exactly FIRE_ROWS rows, whatever the payload says. The canvas is fixed
  # because redraw in place is `ESC[7A` and nothing else: a frame that emitted
  # six rows would walk the cursor up the screen one line per tick.
  while [ "$fire_i" -lt "$FIRE_ROWS" ]; do
    case $fire_rest in
      *"$NL"*)
        fire_line=${fire_rest%%"$NL"*}
        fire_rest=${fire_rest#*"$NL"}
        ;;
      *)
        fire_line=$fire_rest
        fire_rest=''
        ;;
    esac
    fire_paint_row "$fire_line"
    if [ "$fire_i" -eq 0 ]; then FIRE_FRAME=$FIRE_ROW; else FIRE_FRAME=$FIRE_FRAME$NL$FIRE_ROW; fi
    fire_i=$((fire_i + 1))
  done
}

# Which of the four stages a whole-percentage progress is in.
fire_stage_of() {
  FIRE_STAGE=0
  for fire_t in $FIRE_STAGE_PCT; do
    if [ "$1" -ge "$fire_t" ]; then FIRE_STAGE=$((FIRE_STAGE + 1)); fi
  done
}

# Draw one tick at $1 percent. The block is redrawn in place: up FIRE_ROWS, then
# every row prefixed with erase-in-line (three bytes, and correct at any window
# width, where padding to 15 columns would not be). The cursor always finishes
# one line BELOW the block, so a terminal scrolling under us cannot desynchronise
# the next `ESC[<n>A`.
#
# Never the alternate screen buffer. It would make this trivial and it is exactly
# wrong: leaving it restores the previous buffer, so everything the installer
# printed — where the app went, what to add to PATH — is gone the instant it
# exits, and anyone scrolling back to audit what a `curl | sh` just did finds
# nothing.
fire_draw() {
  fire_stage_of "$1"
  eval "fire_fl=\$FIRE_FLICK_$((FIRE_TICK % FIRE_FLICK_N))"
  fire_frame_text "$((FIRE_STAGE * FIRE_STRIDE + fire_fl))"
  fire_out=$ESC'['$FIRE_ROWS'A'
  fire_rest=$FIRE_FRAME
  fire_i=0
  while [ "$fire_i" -lt "$FIRE_ROWS" ]; do
    case $fire_rest in
      *"$NL"*)
        fire_line=${fire_rest%%"$NL"*}
        fire_rest=${fire_rest#*"$NL"}
        ;;
      *)
        fire_line=$fire_rest
        fire_rest=''
        ;;
    esac
    fire_out=$fire_out$ESC'[K'$fire_line$NL
    fire_i=$((fire_i + 1))
  done
  printf '%s' "$fire_out"
  FIRE_TICK=$((FIRE_TICK + 1))
}

# Hide the cursor and make the canvas exist before drawing into it, so whatever
# scrolling is going to happen has already happened and "up FIRE_ROWS" is right
# from the first frame on.
fire_open() {
  if [ "$FIRE_ANIMATE" != 1 ]; then return 0; fi
  FIRE_OPEN=1
  # `$ESC'['` and never "$ESC[": zsh reads `$NAME[` as an array subscript even
  # inside double quotes, so `"$ESC[?25l"` is `zsh: invalid subscript` and the
  # fire dies on its first byte. It is the same hazard as the word splitting at
  # the top of this file and `setopt sh_word_split` does NOT cover it. Both
  # sites are on the animate path, so neither a pipe nor any offline flag can
  # reach them: it took a real pty. `fire_draw` below was already written this
  # way, which is the only reason it was not a third.
  printf '%s' "$ESC"'[?25l'
  fire_i=0
  while [ "$fire_i" -lt "$FIRE_ROWS" ]; do
    printf '\n'
    fire_i=$((fire_i + 1))
  done
}

# Cursor FIRST, before anything else that could itself fail, and idempotent
# because every trap and `die` calls it.
fire_cleanup() {
  if [ "$FIRE_OPEN" = 1 ]; then
    FIRE_OPEN=0
    printf '%s' "$ESC"'[?25h'"$ESC$SGR_RESET"
  fi
}

# --- the degraded path ---------------------------------------------------

PLAIN_LAST=-1

# Bytes as MB (10^6, which is what the label says), one decimal, rounded.
mb_of() {
  plain_tenths=$((($1 + 50000) / 100000))
  printf '%s.%s' "$((plain_tenths / 10))" "$((plain_tenths % 10))"
}

# One line per decile, append-only, no \r and no escape byte, so `tee`, a CI log
# and a support paste all show the same thing afterwards. The loop ticks eight
# times a second and this prints on a decile change and nothing else.
#
# With no total there is no percentage — just the megabytes, every 10 MB. A
# fabricated percent in a log somebody later reads back is worse than no percent.
plain_tick() {
  if [ "$2" -gt 0 ]; then
    plain_dec=$(($1 * 10 / $2))
    if [ "$plain_dec" -gt 10 ]; then plain_dec=10; fi
  else
    plain_dec=$(($1 / 10000000))
  fi
  if [ "$plain_dec" -le "$PLAIN_LAST" ]; then return 0; fi
  PLAIN_LAST=$plain_dec
  if [ "$2" -gt 0 ]; then
    printf '  %5s  %s MB\n' "$((plain_dec * 10))%" "$(mb_of "$1")"
  else
    printf '  %8s MB\n' "$(mb_of "$1")"
  fi
}

# --- fetching ------------------------------------------------------------

HTTP=''

pick_http() {
  if command -v curl >/dev/null 2>&1; then
    HTTP=curl
  elif command -v wget >/dev/null 2>&1; then
    HTTP=wget
  else
    die 'Neither curl nor wget is installed, so there is no way to download anything.' \
      'Install one of them and run this again.'
  fi
}

# What curl or wget last said, for a caller that is about to explain a failure
# in its own words. Empty when they said nothing.
#
# The downloader's stderr is captured rather than let through for two reasons.
# A 404 on latest-linux.yml is an EXPECTED, handled outcome — there is no Linux
# build yet — and `curl: (56) The requested URL returned error: 404` printed
# above the sentence that explains it reads like a failure the script did not
# handle. And during the download, anything written to the terminal mid-frame
# lands inside the campfire's canvas and smears it.
fetch_said() {
  if [ -s "$TMPD/fetch.err" ]; then
    printf '  %s\n' '' 'It said:' >&2
    sed 's/^/    /' "$TMPD/fetch.err" >&2
  fi
}

# Fetch $1 to $2, quietly. Fails on any HTTP error status rather than writing the
# error page to the file.
fetch_quiet() {
  : >"$TMPD/fetch.err"
  if [ "$HTTP" = curl ]; then
    curl -fsSL --proto '=https' -o "$2" "$1" 2>"$TMPD/fetch.err"
  else
    wget -q --max-redirect=10 -O "$2" "$1" 2>"$TMPD/fetch.err"
  fi
}

# Fetch $1 to $2 with the fire burning against a known total of $3 bytes.
#
# The byte counter is `wc -c` on the part-written file, once per frame. That is
# one fork eight times a second — against the fifty a per-glyph `awk` colouring
# pass would cost — and it is the only thing a POSIX shell can ask about a file's
# size at all.
fetch_loud() {
  loud_url=$1
  loud_dest=$2
  loud_total=$3
  : >"$loud_dest"
  : >"$TMPD/fetch.err"
  if [ "$HTTP" = curl ]; then
    curl -fsSL --proto '=https' -o "$loud_dest" "$loud_url" 2>"$TMPD/fetch.err" &
  else
    wget -q --max-redirect=10 -O "$loud_dest" "$loud_url" 2>"$TMPD/fetch.err" &
  fi
  loud_pid=$!
  fire_open
  while kill -0 "$loud_pid" 2>/dev/null; do
    set -- $(wc -c <"$loud_dest" 2>/dev/null || echo 0)
    loud_got=${1:-0}
    if [ "$loud_total" -gt 0 ]; then
      loud_pct=$((loud_got * 100 / loud_total))
      if [ "$loud_pct" -gt 100 ]; then loud_pct=100; fi
    else
      loud_pct=0
    fi
    if [ "$FIRE_ANIMATE" = 1 ]; then
      fire_draw "$loud_pct"
    else
      plain_tick "$loud_got" "$loud_total"
    fi
    sleep "$FIRE_SLEEP"
  done
  if ! wait "$loud_pid"; then
    fire_cleanup
    fetch_said
    die "The download failed: $loud_url" \
      'Nothing has been installed. Try again, or download it by hand from' \
      "  $STOKE_RELEASES"
  fi
  # The last reading belongs to the download being OVER, not to a tick landing
  # on the final byte: without this, a run whose last tick read 99.6% never
  # shows a full fire or a 100% line.
  set -- $(wc -c <"$loud_dest")
  loud_got=${1:-0}
  if [ "$FIRE_ANIMATE" = 1 ]; then
    fire_draw 100
    fire_cleanup
  else
    plain_tick "$loud_got" "$loud_total"
  fi
}

# --- digests -------------------------------------------------------------

# A file's sha512 as BASE64 of the raw 64-byte digest, which is the form
# electron-builder writes into latest*.yml.
#
# This is the single most likely thing in the whole script to be got wrong, and
# it fails 100% of the time when it is: every reflex — `shasum -a 512`,
# `sha512sum`, `Get-FileHash` — produces HEX, and a hex string compared against
# the manifest never matches, which reads exactly like a corrupted download.
sha512_base64() {
  if command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha512 -binary "$1" | openssl base64 -A
    return 0
  fi
  # No openssl: go the long way round, hex digest -> raw bytes -> base64.
  if command -v shasum >/dev/null 2>&1; then
    sha_hex=$(shasum -a 512 "$1" | cut -d' ' -f1)
  elif command -v sha512sum >/dev/null 2>&1; then
    sha_hex=$(sha512sum "$1" | cut -d' ' -f1)
  else
    die 'No openssl, shasum or sha512sum here, so the download cannot be verified.' \
      'Refusing to install something unverified.'
  fi
  if command -v xxd >/dev/null 2>&1; then
    printf '%s' "$sha_hex" | xxd -r -p | base64 | tr -d '\n'
  else
    die 'No openssl and no xxd, so a hex digest cannot be turned into the base64' \
      'form the release manifest uses. Refusing to install something unverified.'
  fi
}

# --- the release manifest ------------------------------------------------

# Fills REL_VERSION, REL_FILE, REL_SHA512 and REL_SIZE from the manifest in $1,
# choosing the file whose name ends in $2 and carries the architecture $3.
#
# Hand-parsed rather than fed to a YAML tool, because there is no YAML tool a
# POSIX shell may assume. The shape is fixed and tiny:
#
#     version: 0.9.4
#     files:
#       - url: Stoke-0.9.4-arm64.zip
#         sha512: B14Hg5HLDSc3...==
#         size: 123361985
#     path: Stoke-0.9.4-arm64.zip
#
# `sha512:` and `size:` are only taken while a `url:` is pending, which is what
# keeps the trailing top-level `sha512:` out of the answer.
read_manifest() {
  REL_VERSION=''
  REL_FILE=''
  REL_SHA512=''
  REL_SIZE=''
  man_url=''
  man_sha=''
  man_size=''
  while IFS= read -r man_line; do
    case $man_line in
      'version: '*) REL_VERSION=${man_line#version: } ;;
      *'- url: '*)
        man_url=${man_line#*- url: }
        man_sha=''
        man_size=''
        ;;
      *'sha512: '*) if [ -n "$man_url" ]; then man_sha=${man_line#*sha512: }; fi ;;
      *'size: '*) if [ -n "$man_url" ]; then man_size=${man_line#*size: }; fi ;;
    esac
    if [ -n "$man_url" ] && [ -n "$man_sha" ] && [ -n "$man_size" ]; then
      if [ -z "$REL_FILE" ] && asset_matches "$man_url" "$2" "$3"; then
        REL_FILE=$man_url
        REL_SHA512=$man_sha
        REL_SIZE=$man_size
      fi
      man_url=''
      man_sha=''
      man_size=''
    fi
  done <"$1"
}

# Whether release file $1 is the one this machine wants: extension $2, arch $3.
#
# macOS names both architectures explicitly (`Stoke-0.9.4-arm64.zip`), because
# electron-builder.yml pins mac's artifactName. Linux does not: electron-builder
# drops the architecture from the DEFAULT arch's name, so the x64 AppImage is
# `Stoke-0.9.5.AppImage` with no arch in it at all, and only arm64 carries one.
asset_matches() {
  case $1 in
    *"$2") : ;;
    *) return 1 ;;
  esac
  case $3 in
    arm64)
      case $1 in
        *arm64* | *aarch64*) return 0 ;;
        *) return 1 ;;
      esac
      ;;
    x64)
      case $1 in
        *x64* | *x86_64* | *amd64*) return 0 ;;
        *arm64* | *aarch64*) return 1 ;;
        # No architecture in the name at all is x64 by electron-builder's own
        # rule, so it counts — but only for x64, never as a fallback for arm64.
        *) return 0 ;;
      esac
      ;;
  esac
  return 1
}

# The numeric part of a version, as three integers in VER_MAJOR/MINOR/PATCH. A
# `-beta.3` suffix is deliberately ignored: comparing prerelease identifiers
# properly is a rabbit hole, and the only thing this comparison has to get right
# is "same" versus "older" versus "newer" on the release line.
version_parts() {
  ver_rest=${1%%-*}
  VER_MAJOR=${ver_rest%%.*}
  ver_rest=${ver_rest#*.}
  VER_MINOR=${ver_rest%%.*}
  VER_PATCH=${ver_rest#*.}
  case $VER_MAJOR in '' | *[!0-9]*) VER_MAJOR=0 ;; esac
  case $VER_MINOR in '' | *[!0-9]*) VER_MINOR=0 ;; esac
  case $VER_PATCH in '' | *[!0-9]*) VER_PATCH=0 ;; esac
}

# -1, 0 or 1 for $1 against $2, in VER_CMP.
version_cmp() {
  version_parts "$1"
  cmp_a=$VER_MAJOR
  cmp_b=$VER_MINOR
  cmp_c=$VER_PATCH
  version_parts "$2"
  VER_CMP=0
  if [ "$cmp_a" -lt "$VER_MAJOR" ]; then VER_CMP=-1
  elif [ "$cmp_a" -gt "$VER_MAJOR" ]; then VER_CMP=1
  elif [ "$cmp_b" -lt "$VER_MINOR" ]; then VER_CMP=-1
  elif [ "$cmp_b" -gt "$VER_MINOR" ]; then VER_CMP=1
  elif [ "$cmp_c" -lt "$VER_PATCH" ]; then VER_CMP=-1
  elif [ "$cmp_c" -gt "$VER_PATCH" ]; then VER_CMP=1
  fi
}

# --- installing ----------------------------------------------------------

# Ask a running Stoke to quit, and wait for it.
#
# NEVER kill it. Stoke's PTYs die with it but the `claude` processes underneath
# do not, and the restarted app cannot reattach to the orphans. Quitting properly
# is what runs `before-quit`, which kills the children and writes the open tabs
# so they come back.
quit_stoke_macos() {
  if ! pgrep -f '/Applications/Stoke.app/Contents/MacOS/Stoke' >/dev/null 2>&1; then
    return 0
  fi
  note 'running' 'asking Stoke to quit so it can close its sessions and save your tabs'
  osascript -e 'quit app "Stoke"' >/dev/null 2>&1 || true
  quit_n=0
  while pgrep -f '/Applications/Stoke.app/Contents/MacOS/Stoke' >/dev/null 2>&1; do
    quit_n=$((quit_n + 1))
    if [ "$quit_n" -gt 60 ]; then
      die 'Stoke is still running after 30 seconds and would not quit.' \
        'Quit it yourself and run this again — killing it would strand the' \
        'claude processes its sessions are running.'
    fi
    sleep 0.5 2>/dev/null || sleep 1
  done
}

install_macos() {
  mac_zip=$1
  mkdir -p "$TMPD/x"
  # ditto over unzip: Apple's own tool, and it preserves the xattrs and the
  # framework symlinks. Both work; this one is the one that is theirs.
  # Both are guarded rather than left to `set -eu`. An unguarded failure here
  # exits the script with nothing on screen but the tool's own one line, which
  # does not say whether anything was installed — and at this point the answer
  # is "no", which is the only thing the reader wants to know.
  mac_unpacked=0
  if command -v ditto >/dev/null 2>&1; then
    if ditto -x -k "$mac_zip" "$TMPD/x"; then mac_unpacked=1; fi
  else
    if unzip -q "$mac_zip" -d "$TMPD/x"; then mac_unpacked=1; fi
  fi
  if [ "$mac_unpacked" != 1 ]; then
    die 'Could not unpack the downloaded archive (its own error is above).' \
      'Nothing has been installed.'
  fi
  mac_app=$TMPD/x/Stoke.app
  if [ ! -d "$mac_app" ]; then
    die 'The downloaded archive did not contain Stoke.app. Nothing has been installed.'
  fi

  # codesign, NEVER spctl. `spctl --assess` rejects every build this project
  # will ever ship — they are signed but not notarized, so it exits 3 by
  # construction and gating on it would refuse every valid install. `codesign
  # --verify --strict --deep` is the check that actually means something: the
  # bundle is intact and signed by the certificate it claims.
  if command -v codesign >/dev/null 2>&1; then
    if codesign --verify --strict --deep "$mac_app" >/dev/null 2>&1; then
      note 'signature' 'codesign --verify --strict --deep: ok'
    else
      die 'The downloaded app failed `codesign --verify --strict --deep`.' \
        'Nothing has been installed. That should never happen with a release' \
        'build — please report it rather than working around it.'
    fi
  fi

  quit_stoke_macos

  # macOS App Management refuses to let a script write inside or delete an app
  # bundle some other installer put in /Applications — measured: `touch` inside
  # a third-party bundle is "Operation not permitted" from a plain shell, while
  # RENAMING it within /Applications is allowed. So: rename aside, put the new
  # one in, then try to remove the old one and carry on if that fails. Leaving a
  # Stoke.app.replaced-NNN behind is far better than aborting the install.
  mac_aside=''
  if [ -e /Applications/Stoke.app ]; then
    mac_aside=/Applications/Stoke.app.replaced-$$
    if ! mv /Applications/Stoke.app "$mac_aside"; then
      die 'Could not move the existing /Applications/Stoke.app out of the way.' \
        'macOS will not let a script replace an app bundle it did not install.' \
        'Drag Stoke.app to the Bin yourself and run this again.'
    fi
  fi
  # And if the new copy does not land, PUT THE OLD ONE BACK. "Rename aside" is
  # only ever an improvement while the replacement arrives; on the path where it
  # does not — a read-only /Applications, a full disk, a ditto that dies — an
  # unguarded copy left the machine with NO /Applications/Stoke.app at all, a
  # Stoke.app.replaced-NNN nobody was told about, and ditto's one line of stderr
  # as the entire explanation. Measured against a relocated copy of this script
  # with a ditto that refuses to write: the app vanished from /Applications and
  # the script said nothing about it.
  mac_landed=0
  if command -v ditto >/dev/null 2>&1; then
    if ditto "$mac_app" /Applications/Stoke.app; then mac_landed=1; fi
  else
    if cp -R "$mac_app" /Applications/Stoke.app; then mac_landed=1; fi
  fi
  if [ "$mac_landed" != 1 ]; then
    # Remove whatever half landed before restoring: it is a bundle THIS script
    # created, so App Management allows it, unlike one another installer put here.
    rm -rf /Applications/Stoke.app 2>/dev/null || true
    if [ -z "$mac_aside" ]; then
      die 'Could not write Stoke into /Applications (its own error is above).' \
        'Nothing has been installed, and nothing that was there has changed.' \
        'Check that /Applications is writable and that the disk is not full.'
    fi
    if mv "$mac_aside" /Applications/Stoke.app 2>/dev/null; then
      die 'Could not write the new Stoke into /Applications (its own error is above).' \
        'The copy you already had has been put back, so nothing has changed.' \
        'Check that /Applications is writable and that the disk is not full.'
    fi
    die 'Could not write the new Stoke into /Applications (its own error is above),' \
      'and the copy you had could not be put back either. It is still on disk, at' \
      "  $mac_aside" \
      'Rename that back to /Applications/Stoke.app, or download a build from' \
      "  $STOKE_RELEASES"
  fi
  if [ -n "$mac_aside" ]; then
    rm -rf "$mac_aside" 2>/dev/null || true
    if [ -e "$mac_aside" ]; then
      note 'left behind' "$mac_aside (macOS would not let this script delete it)"
    fi
  fi

  clear_pending "$HOME/Library/Caches/stoke-updater/pending"
  note 'installed' '/Applications/Stoke.app'
}

install_linux() {
  lin_src=$1
  lin_bin=$HOME/.local/bin/stoke
  # NO VERSION IN THE FILENAME, and that is load-bearing rather than tidy.
  # electron-updater's AppImageUpdater overwrites the running AppImage in place
  # only when the existing name carries no `<n>.<n>.<n>` in it; with a version
  # in the name it writes a NEW file beside the old one, and the .desktop entry
  # and everything on PATH keep pointing at the stale binary forever.
  #
  # Copy into the TARGET directory and rename, rather than `mv` from the temp
  # dir, and that is not tidiness either. $TMPDIR is /tmp on nearly every Linux
  # and is nearly always a different filesystem from $HOME, so `mv` there is a
  # COPY: it opens ~/.local/bin/stoke for writing, which is ETXTBSY ("Text file
  # busy") for as long as Stoke is running, and a copy that fails part way
  # leaves a truncated binary where the working one was. A rename WITHIN one
  # directory is atomic and replaces a running AppImage perfectly happily — the
  # running process keeps the old inode until it exits, which is also why this
  # script never asks Stoke to quit on Linux.
  lin_stage=$HOME/.local/bin/.stoke.new.$$
  if ! mkdir -p "$HOME/.local/bin" || ! cp "$lin_src" "$lin_stage"; then
    rm -f "$lin_stage" 2>/dev/null || true
    die "Could not write to $HOME/.local/bin (its own error is above)." \
      'Nothing has been installed, and anything already there is untouched.'
  fi
  chmod +x "$lin_stage"
  if ! mv -f "$lin_stage" "$lin_bin"; then
    rm -f "$lin_stage" 2>/dev/null || true
    die "Could not replace $lin_bin (its own error is above)." \
      'Nothing has been installed, and the copy you had is untouched.'
  fi

  mkdir -p "$HOME/.local/share/applications" "$HOME/.local/share/icons/hicolor/512x512/apps"
  # Best effort: the AppImage carries its own icon at the root. `--appimage-extract`
  # needs no FUSE, so this works even where running the app would not.
  if (cd "$TMPD" && "$lin_bin" --appimage-extract stoke.png >/dev/null 2>&1); then
    if [ -f "$TMPD/squashfs-root/stoke.png" ]; then
      cp "$TMPD/squashfs-root/stoke.png" "$HOME/.local/share/icons/hicolor/512x512/apps/stoke.png"
    fi
  fi
  cat >"$HOME/.local/share/applications/stoke.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=Stoke
Comment=A desktop shell for Claude Code
Exec=$lin_bin %U
Icon=stoke
Terminal=false
Categories=Development;
StartupWMClass=Stoke
DESKTOP
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$HOME/.local/share/applications" >/dev/null 2>&1 || true
  fi

  # The one place an installed version is recorded on Linux: an AppImage has no
  # Info.plist and no registry, and asking the app itself would mean launching
  # an Electron binary to read one string out of it.
  mkdir -p "$HOME/.local/share/stoke"
  printf '%s\n' "$REL_VERSION" >"$HOME/.local/share/stoke/installed-version"

  clear_pending "${XDG_CACHE_HOME:-$HOME/.cache}/stoke-updater/pending"
  note 'installed' "$lin_bin"

  case ":${PATH}:" in
    *":$HOME/.local/bin:"*) : ;;
    *)
      blank
      say "  ~/.local/bin is not on your PATH, so typing 'stoke' will not find it yet."
      say '  Add this to your shell profile:'
      blank
      say '      export PATH="$HOME/.local/bin:$PATH"'
      ;;
  esac
}

# Anything electron-updater has already staged has to go, or the next quit
# installs THAT over what this script just put down. Stoke sets
# autoInstallOnAppQuit, so a build downloaded in the update panel and not yet
# applied is sitting in this directory waiting to win.
clear_pending() {
  if [ -d "$1" ]; then
    rm -rf "$1" 2>/dev/null || true
    note 'cleared' "a staged update in $1"
  fi
}

# --- the debugging flags -------------------------------------------------

# `--print-plan [tty|pipe]`: what the fire would do. The tty-ness is an argument
# rather than a measurement so that a suite with no terminal can still ask what
# this script does on one — the same reason campfire.ts takes `Terminal.isTty`.
do_print_plan() {
  case ${1:-} in
    tty | pipe) plan_tty=$1 ;;
    '') if [ -t 1 ]; then plan_tty=tty; else plan_tty=pipe; fi ;;
    *) die "--print-plan takes tty or pipe, not $1" ;;
  esac
  fire_plan "$plan_tty"
  printf 'animate=%s\n' "$FIRE_ANIMATE"
  printf 'color=%s\n' "$FIRE_COLOR"
  printf 'reason=%s\n' "$FIRE_WHY"
}

# `--fire-frames TIER`: the twelve frames, painted, seven lines each and nothing
# else — so `--fire-frames none` is a file with no escape byte in it, and the
# other three can be diffed against campfire.ts's own `paint()`.
do_fire_frames() {
  case ${1:-} in
    truecolor | ansi256 | ansi16 | none) fire_set_tier "$1" ;;
    *) die 'usage: --fire-frames truecolor|ansi256|ansi16|none' ;;
  esac
  frames_n=0
  while [ "$frames_n" -lt 12 ]; do
    fire_frame_text "$frames_n"
    printf '%s\n' "$FIRE_FRAME"
    frames_n=$((frames_n + 1))
  done
}

# --- main ----------------------------------------------------------------

main() {
  case ${1:-} in
    --help | -h)
      usage
      return 0
      ;;
    --print-plan)
      do_print_plan "${2:-}"
      return 0
      ;;
    --fire-frames)
      do_fire_frames "${2:-}"
      return 0
      ;;
    --sha512)
      if [ -z "${2:-}" ] || [ ! -f "$2" ]; then die 'usage: --sha512 <file>'; fi
      sha512_base64 "$2"
      printf '\n'
      return 0
      ;;
    '') : ;;
    *) die "Unknown option: $1" 'Run with --help to see what this understands.' ;;
  esac

  # Windows first, because sniffing cannot catch it: curl.exe ships in every
  # Windows 10 1803+ and sends `curl/8.x`, indistinguishable from curl on Linux,
  # so stoke.vinn.dev hands it THIS script. Say what to run instead.
  case "$(uname -s 2>/dev/null || echo unknown)" in
    MINGW* | MSYS* | CYGWIN* | Windows_NT)
      die 'This is the macOS and Linux installer, and this looks like Windows.' \
        'Run this in PowerShell instead:' \
        '' \
        "    $STOKE_PS1_LINE"
      ;;
  esac
  if [ "${OS:-}" = Windows_NT ]; then
    die 'This is the macOS and Linux installer, and this looks like Windows.' \
      'Run this in PowerShell instead:' \
      '' \
      "    $STOKE_PS1_LINE"
  fi

  case "$(uname -s)" in
    Darwin) PLATFORM=mac ;;
    Linux) PLATFORM=linux ;;
    *) die "Stoke has no build for $(uname -s)." "There are builds for macOS and Windows at $STOKE_RELEASES" ;;
  esac

  ARCH=''
  case "$(uname -m)" in
    arm64 | aarch64) ARCH=arm64 ;;
    x86_64 | amd64) ARCH=x64 ;;
    *) die "Stoke has no build for a $(uname -m) CPU." ;;
  esac
  # A shell running under Rosetta reports x86_64 on an Apple Silicon Mac, and
  # installing the Intel build there would be both slower and — while the
  # release matrix is still arm64-only — an outright refusal on a machine that
  # can run Stoke perfectly well.
  if [ "$PLATFORM" = mac ] && [ "$ARCH" = x64 ]; then
    if [ "$(sysctl -n sysctl.proc_translated 2>/dev/null || echo 0)" = 1 ]; then
      ARCH=arm64
    fi
  fi

  if [ -t 1 ]; then fire_plan tty; else fire_plan pipe; fi
  # The frame interval comes from the art block (FIRE_MS), so the shell and
  # src/shared/campfire.ts cannot disagree about how fast the fire burns. POSIX
  # `sleep` takes an integer; every implementation that matters takes a fraction,
  # but busybox ash on an old image might not, and a one-second fire is better
  # than an error.
  if sleep 0.05 2>/dev/null; then
    FIRE_SLEEP=$(printf '0.%03d' "$FIRE_MS")
  else
    FIRE_SLEEP=1
  fi

  pick_http

  TMPD=$(mktemp -d "${TMPDIR:-/tmp}/stoke-install.XXXXXX")
  trap 'fire_cleanup; rm -rf "$TMPD"' EXIT
  trap 'fire_cleanup; rm -rf "$TMPD"; exit 130' INT
  trap 'fire_cleanup; rm -rf "$TMPD"; exit 143' TERM
  trap 'fire_cleanup; rm -rf "$TMPD"; exit 129' HUP

  blank
  say '  stoke'
  blank

  # Which update manifest describes this machine's build. These are the same
  # files electron-updater itself reads, so the script and the app agree about
  # what "latest" means by construction rather than by a second convention.
  case $PLATFORM in
    mac) MANIFEST=latest-mac.yml; WANT_EXT=.zip ;;
    linux)
      WANT_EXT=.AppImage
      if [ "$ARCH" = arm64 ]; then MANIFEST=latest-linux-arm64.yml; else MANIFEST=latest-linux.yml; fi
      ;;
  esac

  if ! fetch_quiet "$STOKE_LATEST_DL/$MANIFEST" "$TMPD/$MANIFEST"; then
    # A missing Linux manifest is an expected answer rather than a fault — the
    # release matrix gained Linux after v0.9.4 — so it gets its own sentence and
    # the downloader's own 404 is not quoted over the top of it.
    #
    # It names the ARCHITECTURE, because the two Linux manifests go missing for
    # different reasons and only one of them is temporary: latest-linux.yml
    # arrives with the next release, while latest-linux-arm64.yml is not built
    # at all (`node scripts/targets.mjs --list`). "There is no Linux build yet"
    # is true today and becomes a lie for an arm64 reader the moment x64 ships.
    if [ "$PLATFORM" = linux ]; then
      die "The latest Stoke release has no Linux $ARCH build." \
        "The macOS and Windows builds are at $STOKE_RELEASES" \
        'Linux AppImages start with the next release; that page lists what each' \
        'one actually has.'
    fi
    fetch_said
    die "Could not fetch $MANIFEST from the latest release." \
      'Check your network, or download a build by hand from' \
      "  $STOKE_RELEASES"
  fi

  # Assert the body is what was asked for before trusting a byte of it.
  # Cloudflare's bot defences — and GitHub's own error pages — answer with HTML
  # and HTTP 200, which `curl -f` does not catch and which a script will happily
  # try to parse. A manifest opens with `version:` and nothing else does.
  if ! grep -q '^version: ' "$TMPD/$MANIFEST"; then
    die "What came back from $MANIFEST is not a release manifest." \
      'Something between here and GitHub is answering for it — a captive portal,' \
      'a proxy, or a bot challenge. Nothing has been downloaded or installed.'
  fi

  read_manifest "$TMPD/$MANIFEST" "$WANT_EXT" "$ARCH"
  if [ -z "$REL_VERSION" ]; then
    die "Could not read a version out of $MANIFEST."
  fi
  if [ -z "$REL_FILE" ]; then
    # The honest sentence, not a 404 later. v0.9.4 is arm64-only on macOS; the
    # five-platform matrix fixes that from the next release onwards.
    die "Stoke $REL_VERSION has no $PLATFORM $ARCH build." \
      "The release lists no ${WANT_EXT#.} for this architecture, so there is nothing to install." \
      "See $STOKE_RELEASES for what it does have."
  fi
  case $REL_FILE in
    Stoke-*) : ;;
    *) die "The manifest names an unexpected file ($REL_FILE). Refusing to download it." ;;
  esac
  case $REL_SIZE in
    '' | *[!0-9]*) die "The manifest gives no usable size for $REL_FILE." ;;
  esac

  # What is already here.
  INSTALLED=''
  if [ "$PLATFORM" = mac ] && [ -d /Applications/Stoke.app ]; then
    INSTALLED=$(defaults read /Applications/Stoke.app/Contents/Info CFBundleShortVersionString 2>/dev/null || true)
  elif [ "$PLATFORM" = linux ] && [ -f "$HOME/.local/share/stoke/installed-version" ]; then
    INSTALLED=$(cat "$HOME/.local/share/stoke/installed-version" 2>/dev/null || true)
  fi

  note 'release' "$REL_VERSION"
  note 'installed' "${INSTALLED:-nothing yet}"
  note 'machine' "$PLATFORM $ARCH"
  note 'file' "$REL_FILE ($(mb_of "$REL_SIZE") MB)"

  if [ -n "$INSTALLED" ] && [ -z "${STOKE_FORCE:-}" ]; then
    version_cmp "$INSTALLED" "$REL_VERSION"
    if [ "$VER_CMP" = 0 ]; then
      if [ -z "${STOKE_DRY_RUN:-}" ]; then
        blank
        say "  Stoke $REL_VERSION is already installed. Nothing to do."
        blank
        return 0
      fi
      note 'note' 'already current — a real run would stop here; this is a dry run, so it carries on'
    elif [ "$VER_CMP" = 1 ]; then
      die "The installed Stoke ($INSTALLED) is newer than the latest release ($REL_VERSION)." \
        'That is usually a local build. Nothing has been changed.' \
        'Run again with STOKE_FORCE=1 to replace it anyway.'
    fi
  fi

  blank
  fetch_loud "$STOKE_LATEST_DL/$REL_FILE" "$TMPD/$REL_FILE" "$REL_SIZE"
  blank

  # Size first: it is free, and a challenge page or a truncated body fails here
  # with a sentence that says which, rather than as a digest mismatch that reads
  # like corruption.
  set -- $(wc -c <"$TMPD/$REL_FILE")
  GOT_SIZE=${1:-0}
  if [ "$GOT_SIZE" != "$REL_SIZE" ]; then
    rm -f "$TMPD/$REL_FILE"
    die "The download is $GOT_SIZE bytes and the release says $REL_SIZE." \
      'The partial file has been deleted and nothing has been installed.'
  fi

  GOT_SHA=$(sha512_base64 "$TMPD/$REL_FILE")
  if [ "$GOT_SHA" != "$REL_SHA512" ]; then
    rm -f "$TMPD/$REL_FILE"
    die 'The download does not match the sha512 in the release manifest.' \
      "  expected  $REL_SHA512" \
      "  got       $GOT_SHA" \
      'The file has been deleted and nothing has been installed.'
  fi
  note 'verified' 'sha512 matches the release manifest'

  if [ -n "${STOKE_DRY_RUN:-}" ]; then
    blank
    say "  STOKE_DRY_RUN: stopping here. $REL_FILE downloaded and verified;"
    say '  nothing was installed and nothing outside the temp directory was touched.'
    blank
    return 0
  fi

  case $PLATFORM in
    mac) install_macos "$TMPD/$REL_FILE" ;;
    linux) install_linux "$TMPD/$REL_FILE" ;;
  esac

  blank
  if [ "$PLATFORM" = mac ]; then
    say "  Stoke $REL_VERSION is installed. Opening it now."
    open /Applications/Stoke.app || true
  else
    say "  Stoke $REL_VERSION is installed. Run 'stoke' to start it."
    say '  If it refuses to start with a FUSE error, run it as'
    say '  `stoke --appimage-extract-and-run` or install libfuse2.'
    # Said out loud because the replacement is a rename and a rename is silent:
    # a running copy keeps the old inode and carries on being the old version
    # with no warning anywhere, which reads as "the upgrade did nothing".
    if pgrep -f "$lin_bin" >/dev/null 2>&1; then
      blank
      say '  Stoke is running, and it is still the build it started as. Quit it and'
      say '  start it again to be on this one. Nothing was killed: its sessions are'
      say '  running claude processes that would be stranded.'
    fi
  fi
  blank
  say '  Run the same one-liner again any time to upgrade.'
  blank
}

main "$@"
