# Stoke, in one line, from Command Prompt, Windows PowerShell or PowerShell 7:
#
#     powershell -ExecutionPolicy Bypass -c "irm https://stoke.vinn.dev | iex"
#
# or, already inside PowerShell, just `irm https://stoke.vinn.dev | iex`. The
# long form exists because `irm` means nothing to cmd.exe, which is where a
# Windows user who opened "a terminal" usually is.
#
# Installs or upgrades Stoke on Windows, under Windows PowerShell 5.1 (the one
# that ships in Windows) and PowerShell 7 alike. macOS and Linux are install.sh;
# this script detects a non-Windows PowerShell and says so rather than failing
# somewhere confusing.
#
# It downloads only from github.com/realvinn/stoke/releases and verifies every
# byte against the sha512 in that release's own update manifest before running
# anything. $env:STOKE_DRY_RUN = '1' does all of that and stops before running
# the installer.
#
# ---------------------------------------------------------------------------
# Everything is inside Install-Stoke, which is called on the LAST line. `iex`
# parses the whole string before executing a statement, so a truncated download
# leaves an unclosed `{` and is a hard parse error rather than half an install —
# and `Invoke-RestMethod` throws on a truncated stream before `iex` sees it at
# all. This shape makes both of those true rather than relying on the second.
#
# NOT VERIFIED ON WINDOWS. Nobody has run this file. There is no PowerShell on
# the machine it was written on, so it has never been parsed by a PowerShell of
# any version, and the NSIS silent-install flags below are read out of
# app-builder-lib's own templates rather than observed. `npm run verify:install`
# checks what can be checked from a Mac — that the art block matches the
# generator byte for byte, that the last line is the call, that the download
# does not go through Invoke-WebRequest, and that the upgrade-detection GUID is
# still the one electron-builder derives from this project's appId — and that is
# genuinely less than running it once.
# ---------------------------------------------------------------------------
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# TLS 1.2, before the first request. Windows PowerShell 5.1 on older Windows
# builds defaults its ServicePointManager to SSL 3.0/TLS 1.0, so a download can
# fail with "Could not create SSL/TLS secure channel" against a modern CDN. The
# -bor keeps whatever the machine already had.
try {
  [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
} catch {
  # .NET 4.6+ resolves SystemDefault to TLS 1.2 anyway; an old enough runtime
  # that cannot name Tls12 is not a machine this can fix from here.
}

# BEGIN CAMPFIRE ART
# Generated by `node scripts/gen-installer-art.mts ps1` from src/shared/campfire.ts.
# DO NOT EDIT BY HAND: verify:campfire asserts this block byte for byte against
# the generator, and a hand-encoded row has already shipped a visible `||` once.
#
# Canvas is a fixed 10 rows x 17 columns for every frame, because redraw in
# place is ESC[10A and nothing else -- a shorter frame walks the cursor up the
# screen a row per tick. Flame rows are stored right-trimmed; emit ESC[K per row
# rather than padding to the full width.
#
# 12 frames: 4 stages (spark kindling burning roaring) x 3 flicker frames.
# Pick with: stage from $FireStagePct against the percentage downloaded,
# flicker from $FireFlicker[$tick % 6], then n = stage * 3 + flicker and
#   $FireF[$n]                (or $FireM[$n] for the monochrome tier).
#
# Rows are segment-encoded as KEY:text|KEY:text, joined by newlines. Keys:
#   _ uncoloured (spaces)   C core (white-hot)   S spark   M mid   B base   L log
# Neither | nor : can appear in the art, so the split is unambiguous.
# $FireM* is the same art with no colour at all, for the monochrome tier.
#
# Print these with [Console]::Out.Write($row), never Write-Host and never a
# format operator -- $PSStyle.OutputRendering strips escape sequences from
# anything PowerShell formats, and the art is full of backslashes.
$FireRows = 10
$FireCols = 17
$FireMs = 125
$FireFlicker = @(0, 1, 2, 1, 0, 2)
$FireStagePct = @(8, 35, 75)
$FireF0 = @'





_:  |C:*|_:     |S:.
_:         |S:^
_:         |B:(|C:#|B:)
'@
$FireF1 = @'





_:   |S:.|_:         |C:*
_:          |S:^
_:         |B:(|C:#|B:)
'@
$FireF2 = @'





_: |S:,|_:    |S:^
_:        |S:^
_:         |B:(|C:#|B:)
'@
$FireF3 = @'




_:  |C:*|_:     |S:.|_:      |S:,
_:         |B:(~)
_:        |B:(+~)
_:       |B:(+|C:#|B:+)
'@
$FireF4 = @'




_:   |S:.|_:         |C:*|_:  |S:^
_:          |B:(~)
_:        |B:(+~)
_:       |B:(+|C:#|B:+)
'@
$FireF5 = @'




_: |S:,|_:    |S:^|_:       |C:*
_:        |B:(~)
_:        |B:(+~)
_:       |B:(+|C:#|B:+)
'@
$FireF6 = @'


_:  |C:*|_:     |S:.|_:      |S:,
_:          |M:(~)
_:         |B:(+~)
_:        |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:      |B:(++|C:#|B:++)
'@
$FireF7 = @'


_:   |S:.|_:         |C:*|_:  |S:^
_:           |M:(~)
_:          |B:(+~)
_:        |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:      |B:(++|C:#|B:++)
'@
$FireF8 = @'


_: |S:,|_:    |S:^|_:       |C:*
_:         |M:(~)
_:        |B:(+~)
_:        |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:      |B:(++|C:#|B:++)
'@
$FireF9 = @'
_:  |C:*|_:     |S:.|_:      |S:,
_:         |S:~|_:    |S:.
_:           |M:(~)
_:         |M:(+~)
_:        |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:   |B:(+)(++|C:#|B:++)
_:     |B:(++|C:###|B:++)
'@
$FireF10 = @'
_:   |S:.|_:         |C:*|_:  |S:^
_:           |S:~|_:   |S:.
_:            |M:(+~~
_:          |M:(+~)
_:         |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:   |B:(+)(++|C:#|B:++)
_:     |B:(++|C:###|B:++)
'@
$FireF11 = @'
_: |S:,|_:    |S:^|_:       |C:*
_:       |S:~|_:     |S:.
_:          |M:~~+)
_:        |M:(+~)
_:       |B:(++~)
_:   |B:(~)|_: |B:(+|C:#|B:+)
_:   |B:(+)(++|C:#|B:++)
_:     |B:(++|C:###|B:++)
'@
$FireFH = @'
L:(===-.,___,.-===)
L:_,.-=========-.,_
'@
$FireM0 = @'





  *     .
         ^
         (#)
'@
$FireM1 = @'





   .         *
          ^
         (#)
'@
$FireM2 = @'





 ,    ^
        ^
         (#)
'@
$FireM3 = @'




  *     .      ,
         (~)
        (+~)
       (+#+)
'@
$FireM4 = @'




   .         *  ^
          (~)
        (+~)
       (+#+)
'@
$FireM5 = @'




 ,    ^       *
        (~)
        (+~)
       (+#+)
'@
$FireM6 = @'


  *     .      ,
          (~)
         (+~)
        (++~)
   (~) (+#+)
      (++#++)
'@
$FireM7 = @'


   .         *  ^
           (~)
          (+~)
        (++~)
   (~) (+#+)
      (++#++)
'@
$FireM8 = @'


 ,    ^       *
         (~)
        (+~)
        (++~)
   (~) (+#+)
      (++#++)
'@
$FireM9 = @'
  *     .      ,
         ~    .
           (~)
         (+~)
        (++~)
   (~) (+#+)
   (+)(++#++)
     (++###++)
'@
$FireM10 = @'
   .         *  ^
           ~   .
            (+~~
          (+~)
         (++~)
   (~) (+#+)
   (+)(++#++)
     (++###++)
'@
$FireM11 = @'
 ,    ^       *
       ~     .
          ~~+)
        (+~)
       (++~)
   (~) (+#+)
   (+)(++#++)
     (++###++)
'@
$FireMH = @'
(===-.,___,.-===)
_,.-=========-.,_
'@
$FireF = @($FireF0, $FireF1, $FireF2, $FireF3, $FireF4, $FireF5, $FireF6, $FireF7, $FireF8, $FireF9, $FireF10, $FireF11)
$FireM = @($FireM0, $FireM1, $FireM2, $FireM3, $FireM4, $FireM5, $FireM6, $FireM7, $FireM8, $FireM9, $FireM10, $FireM11)
# The palette, as the bytes AFTER ESC. ESC itself is [char]27; write it with
# [Console]::Out.Write, never Write-Host -- $PSStyle.OutputRendering strips
# escape sequences from anything PowerShell formats.
$FireSgr = @{
  truecolor = @{ C = '[38;2;255;243;226m'; S = '[38;2;255;196;140m'; M = '[38;2;255;149;82m'; B = '[38;2;232;95;36m'; L = '[38;2;124;58;29m' }
  ansi256 = @{ C = '[38;5;230m'; S = '[38;5;216m'; M = '[38;5;209m'; B = '[38;5;166m'; L = '[38;5;94m' }
  ansi16 = @{ C = '[1;37m'; S = '[1;33m'; M = '[0;33m'; B = '[1;31m'; L = '[0;31m' }
}
$FireReset = '[0m'
# END CAMPFIRE ART

# How many flicker frames each stage has, so `n = stage * $FireStride + flicker`
# addresses the right one of the twelve. The art block states the formula in its
# preamble but carries no variable for the stride; verify:install asserts this
# against campfire.ts's own stage shape, and against install.sh's copy of it.
$FireStride = 3

$StokeReleases = 'https://github.com/realvinn/stoke/releases'
$StokeLatestDownload = "$StokeReleases/latest/download"
$StokeShLine = 'curl -fsSL https://stoke.vinn.dev | sh'
$Esc = [char]27

# The registry key electron-builder's NSIS installer records itself under.
#
# It is UUIDv5(appId, 50e065bc-3134-11e6-9bab-38c9862bdaf3) — NsisTarget.js:28,157
# — over `appId: dev.vinn.stoke` from electron-builder.yml. Hardcoded here
# because deriving a v5 UUID needs a SHA-1 of a namespace concatenation and this
# script cannot be tested on the machine it was written on, and pinned by
# verify:install, which recomputes it from electron-builder.yml. Without that
# pin, changing appId would silently stop upgrade detection working while fresh
# installs carried on succeeding, so nobody would notice.
$AppGuid = '27e02fae-12b6-525c-aa7f-c00dfad6e928'

function Install-Stoke {
  # --- where are we ------------------------------------------------------

  # $IsWindows does not exist in Windows PowerShell 5.1, and Set-StrictMode
  # makes reading a missing variable an error, so it cannot simply be tested.
  # -or short-circuits, but the version test has to come first and stand alone.
  $onWindows = $true
  if ($PSVersionTable.PSVersion.Major -ge 6) { $onWindows = $IsWindows }
  if (-not $onWindows) {
    Write-Host ''
    Write-Host '  This is the Windows installer, and this is not Windows.'
    Write-Host '  Run this instead:'
    Write-Host ''
    Write-Host "      $StokeShLine"
    Write-Host ''
    return
  }

  # Inside Stoke's own terminal, the close below (which installing has to do)
  # ends every session Stoke is running -- including the one running this, so
  # the install would stop halfway. Said before anything is downloaded. A dry
  # run closes nothing, so it may carry on.
  if ($env:TERM_PROGRAM -eq 'Stoke' -and -not $env:STOKE_DRY_RUN) {
    Write-Host ''
    Write-Host '  This terminal is inside Stoke, so this installer cannot replace it.'
    Write-Host ''
    Write-Host '  Installing closes Stoke so the new copy can go in, and closing Stoke ends'
    Write-Host '  every session it is running - this one included.'
    Write-Host ''
    Write-Host '  Use Settings > Updates in Stoke instead, or run the same line from a'
    Write-Host '  PowerShell window outside Stoke.'
    Write-Host ''
    return
  }

  $arch = 'x64'
  if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64' -or $env:PROCESSOR_ARCHITEW6432 -eq 'ARM64') {
    $arch = 'arm64'
  }

  $plan = Get-FirePlan
  $tmp = Join-Path ([IO.Path]::GetTempPath()) ("stoke-install-" + [Guid]::NewGuid().ToString('N'))
  New-Item -ItemType Directory -Path $tmp -Force | Out-Null

  try {
    Write-Host ''
    Write-Host '  stoke'
    Write-Host ''

    # --- what is the latest release ---------------------------------------

    # latest.yml is the same feed the installed app's updater reads, so the
    # script and the app agree about what "latest" means by construction. The
    # /releases/latest/download/ redirect needs no API token and has no rate
    # limit worth thinking about.
    $manifestText = Invoke-RestMethod -Uri "$StokeLatestDownload/latest.yml" -UseBasicParsing

    # Assert the body is a manifest before trusting a byte of it. Cloudflare's
    # bot defences answer a challenge with HTML and HTTP 200, which no error
    # handling catches, and GitHub's own error pages are HTML too.
    if ($manifestText -isnot [string] -or $manifestText -notmatch '(?m)^version:\s') {
      throw "What came back for latest.yml is not a release manifest. Something between here and GitHub is answering for it - a proxy, a captive portal or a bot challenge. Nothing has been downloaded."
    }

    $release = Read-StokeManifest -Text $manifestText -Extension '.exe' -Arch $arch
    if (-not $release.Version) { throw 'Could not read a version out of latest.yml.' }
    if (-not $release.File) {
      throw "Stoke $($release.Version) has no Windows $arch build. The release lists no installer for this architecture, so there is nothing to install. See $StokeReleases"
    }
    if ($release.File -notlike 'Stoke-*') {
      throw "The manifest names an unexpected file ($($release.File)). Refusing to download it."
    }

    $installed = Get-InstalledStoke
    Write-Row 'release' $release.Version
    Write-Row 'installed' $(if ($installed.Version) { $installed.Version } else { 'nothing yet' })
    Write-Row 'machine' "windows $arch"
    Write-Row 'file' ("{0} ({1} MB)" -f $release.File, (Format-Mb $release.Size))

    if ($installed.PerMachine) {
      Write-Row 'note' 'the existing Stoke was installed for all users, so Windows will ask for administrator rights'
    }

    if ($installed.Version -and -not $env:STOKE_FORCE) {
      $cmp = Compare-StokeVersion $installed.Version $release.Version
      if ($cmp -eq 0) {
        if (-not $env:STOKE_DRY_RUN) {
          Write-Host ''
          Write-Host "  Stoke $($release.Version) is already installed. Nothing to do."
          Write-Host ''
          return
        }
        Write-Row 'note' 'already current - a real run would stop here; this is a dry run, so it carries on'
      } elseif ($cmp -gt 0) {
        throw "The installed Stoke ($($installed.Version)) is newer than the latest release ($($release.Version)). That is usually a local build, so nothing has been changed. Set `$env:STOKE_FORCE = '1' to replace it anyway."
      }
    }

    # --- download ----------------------------------------------------------

    $exe = Join-Path $tmp $release.File
    Write-Host ''
    Get-StokeDownload -Uri "$StokeLatestDownload/$($release.File)" -OutFile $exe -Total $release.Size -Plan $plan
    Write-Host ''

    $got = (Get-Item $exe).Length
    if ($got -ne $release.Size) {
      Remove-Item $exe -Force -ErrorAction SilentlyContinue
      throw "The download is $got bytes and the release says $($release.Size). The partial file has been deleted and nothing has been installed."
    }

    $digest = Get-Sha512Base64 $exe
    if ($digest -ne $release.Sha512) {
      Remove-Item $exe -Force -ErrorAction SilentlyContinue
      throw "The download does not match the sha512 in the release manifest.`n  expected  $($release.Sha512)`n  got       $digest`nThe file has been deleted and nothing has been installed."
    }
    Write-Row 'verified' 'sha512 matches the release manifest'

    if ($env:STOKE_DRY_RUN) {
      Write-Host ''
      Write-Host "  STOKE_DRY_RUN: stopping here. $($release.File) downloaded and verified;"
      Write-Host '  nothing was installed.'
      Write-Host ''
      return
    }

    # --- install -----------------------------------------------------------

    Stop-StokeGracefully

    # /S and nothing else.
    #
    # No /allusers: with perMachine false the installer's manifest is
    # RequestExecutionLevel user, and /allusers under /S sends it down the
    # elevation path - a UAC prompt out of a one-liner.
    #
    # No /D= on an upgrade either: the installer reads the previous
    # InstallLocation out of the registry and reuses it, so passing a directory
    # can only ever move an install the user had put somewhere deliberately.
    Write-Row 'installing' 'running the installer silently'
    $proc = Start-Process -FilePath $exe -ArgumentList '/S' -Wait -PassThru
    if ($proc.ExitCode -ne 0) {
      throw "The installer exited with code $($proc.ExitCode). Run it by hand to see what it says: $exe"
    }

    # Anything electron-updater has already staged has to go, or the next quit
    # installs THAT over what this script just put down: Stoke sets
    # autoInstallOnAppQuit, so a build downloaded in the update panel and not
    # yet applied is sitting in this directory waiting to win.
    $pending = Join-Path $env:LOCALAPPDATA 'stoke-updater\pending'
    if (Test-Path $pending) {
      Remove-Item $pending -Recurse -Force -ErrorAction SilentlyContinue
      Write-Row 'cleared' "a staged update in $pending"
    }

    $after = Get-InstalledStoke
    if ($after.Location) {
      Write-Row 'installed' $after.Location
      Add-StokeToPath (Join-Path $after.Location 'resources\bin')
    }

    Write-Host ''
    Write-Host "  Stoke $($release.Version) is installed."
    if ($after.Location) {
      $app = Join-Path $after.Location 'Stoke.exe'
      if (Test-Path $app) { Start-Process -FilePath $app }
    }
    Write-Host ''
    Write-Host '  Run the same one-liner again any time to upgrade.'
    Write-Host ''
  } finally {
    # Cursor FIRST, before anything that could itself fail.
    Reset-Fire
    Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
  }
}

# --- talking ---------------------------------------------------------------

function Write-Row([string]$Label, [string]$Value) {
  Write-Host ("  {0,-11} {1}" -f $Label, $Value)
}

function Format-Mb([double]$Bytes) {
  return [math]::Round($Bytes / 1e6, 1).ToString([Globalization.CultureInfo]::InvariantCulture)
}

# --- the release manifest --------------------------------------------------

# latest.yml, hand-parsed. Its shape is fixed and tiny, and there is no YAML
# parser a bare PowerShell may assume:
#
#     version: 0.9.4
#     files:
#       - url: Stoke-0.9.4-x64-setup.exe
#         sha512: EakW6ulw/k4J7EXuzjTejzbQw2n3PcM+nmJfZm2yEV5dh4h/AYnoYr4WRdzVwB/XKILYG56w4Dn54O6FaeAESA==
#         size: 102576420
#     path: Stoke-0.9.4-x64-setup.exe
#
# sha512 and size are only taken while a url is pending, which is what keeps the
# trailing top-level sha512 out of the answer.
function Read-StokeManifest([string]$Text, [string]$Extension, [string]$Arch) {
  $result = [pscustomobject]@{ Version = ''; File = ''; Sha512 = ''; Size = 0 }
  $url = ''
  $sha = ''
  $size = ''
  foreach ($line in ($Text -split "\r?\n")) {
    if ($line -match '^version:\s*(.+?)\s*$') { $result.Version = $Matches[1] }
    elseif ($line -match '^\s*-\s*url:\s*(.+?)\s*$') { $url = $Matches[1]; $sha = ''; $size = '' }
    elseif ($url -and $line -match '^\s*sha512:\s*(.+?)\s*$') { $sha = $Matches[1] }
    elseif ($url -and $line -match '^\s*size:\s*(\d+)\s*$') { $size = $Matches[1] }
    if ($url -and $sha -and $size) {
      if (-not $result.File -and (Test-StokeAsset -Name $url -Extension $Extension -Arch $Arch)) {
        $result.File = $url
        $result.Sha512 = $sha
        $result.Size = [int64]$size
      }
      $url = ''; $sha = ''; $size = ''
    }
  }
  return $result
}

# Windows names both architectures explicitly, because electron-builder.yml pins
# win's artifactName to ${productName}-${version}-${arch}-setup.${ext}.
function Test-StokeAsset([string]$Name, [string]$Extension, [string]$Arch) {
  if (-not $Name.EndsWith($Extension)) { return $false }
  if ($Arch -eq 'arm64') { return ($Name -match 'arm64') }
  if ($Name -match 'arm64') { return $false }
  return ($Name -match 'x64|x86_64|amd64')
}

# The numeric part only. A -beta.3 suffix is ignored: comparing prerelease
# identifiers properly is a rabbit hole, and all this has to get right is
# same/older/newer on the release line.
function Compare-StokeVersion([string]$A, [string]$B) {
  $pa = ($A -split '-')[0] -split '\.'
  $pb = ($B -split '-')[0] -split '\.'
  for ($i = 0; $i -lt 3; $i++) {
    $x = 0; $y = 0
    if ($i -lt $pa.Count) { [void][int]::TryParse($pa[$i], [ref]$x) }
    if ($i -lt $pb.Count) { [void][int]::TryParse($pb[$i], [ref]$y) }
    if ($x -lt $y) { return -1 }
    if ($x -gt $y) { return 1 }
  }
  return 0
}

# --- what is already here --------------------------------------------------

# Both scopes, and which one matters. HKCU is the ordinary case (perMachine is
# false). HKLM means somebody installed it for all users, and re-running the
# installer there needs elevation - so it is reported before the download rather
# than discovered as a UAC prompt out of a one-liner.
function Get-InstalledStoke {
  $out = [pscustomobject]@{ Version = ''; Location = ''; PerMachine = $false }
  foreach ($root in @('HKCU:', 'HKLM:')) {
    $uninstall = "$root\Software\Microsoft\Windows\CurrentVersion\Uninstall\$AppGuid"
    $install = "$root\Software\$AppGuid"
    try {
      if (Test-Path $uninstall) {
        $key = Get-ItemProperty -Path $uninstall -ErrorAction Stop
        if ($key.PSObject.Properties.Name -contains 'DisplayVersion' -and -not $out.Version) {
          $out.Version = [string]$key.DisplayVersion
          $out.PerMachine = ($root -eq 'HKLM:')
        }
      }
      if (Test-Path $install) {
        $key = Get-ItemProperty -Path $install -ErrorAction Stop
        if ($key.PSObject.Properties.Name -contains 'InstallLocation' -and -not $out.Location) {
          $out.Location = [string]$key.InstallLocation
        }
      }
    } catch {
      # An unreadable key is "we do not know", never "it is not installed".
    }
  }
  return $out
}

# Ask Stoke to close, and wait.
#
# NEVER kill it, and do not let the installer do the killing either. Stoke's
# PTYs die with it but the `claude` processes underneath do not, and the
# restarted app cannot reattach to the orphans. NSIS's own "please close it"
# prompt takes the default under /S and force-stops everything under $INSTDIR,
# which is exactly that failure - so close it first and leave NSIS nothing to do.
function Stop-StokeGracefully {
  $procs = @(Get-Process -Name 'Stoke' -ErrorAction SilentlyContinue)
  if ($procs.Count -eq 0) { return }
  Write-Row 'running' 'asking Stoke to close so it can end its sessions and save your tabs'
  foreach ($p in $procs) {
    try { [void]$p.CloseMainWindow() } catch { }
  }
  for ($i = 0; $i -lt 60; $i++) {
    Start-Sleep -Milliseconds 500
    if (@(Get-Process -Name 'Stoke' -ErrorAction SilentlyContinue).Count -eq 0) { return }
  }
  throw 'Stoke is still running after 30 seconds and would not close. Close it yourself and run this again - killing it would strand the claude processes its sessions are running.'
}

# --- the stoke command -----------------------------------------------------

# <install>\resources\bin\stoke.cmd, on the per-user PATH. The same edit as
# Settings > Updates > Command line in the app (src/main/stokeCommand.ts).
#
# Read RAW and written back as REG_EXPAND_SZ: the obvious
# [Environment]::GetEnvironmentVariable / SetEnvironmentVariable round trip
# returns the value expanded and writes a plain REG_SZ, which freezes
# %USERPROFILE%\AppData\Local\Microsoft\WindowsApps -- the entry Windows puts
# there itself -- and every other %VAR% entry into a literal, for good. The
# change is then announced by setting and clearing a throwaway variable
# through [Environment], which broadcasts WM_SETTINGCHANGE; a raw registry
# write does not. Never setx, which truncates the value at 1024 characters.
#
# Never fatal: Stoke is installed whether or not this lands.
function Add-StokeToPath([string]$Dir) {
  if (-not (Test-Path -LiteralPath (Join-Path $Dir 'stoke.cmd'))) {
    Write-Row 'command' 'this release has no stoke command yet'
    return
  }
  try {
    $key = [Microsoft.Win32.Registry]::CurrentUser.CreateSubKey('Environment')
    try {
      $raw = [string]$key.GetValue('Path', '', [Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
      $parts = @($raw -split ';' | Where-Object { $_ -ne '' })
      $want = $Dir.TrimEnd('\').ToLowerInvariant()
      $have = @($parts | Where-Object { ([Environment]::ExpandEnvironmentVariables($_)).TrimEnd('\').ToLowerInvariant() -eq $want })
      if ($have.Count -gt 0) {
        Write-Row 'command' 'stoke (its folder is already on your PATH)'
        return
      }
      $key.SetValue('Path', (($parts + $Dir) -join ';'), [Microsoft.Win32.RegistryValueKind]::ExpandString)
    } finally {
      $key.Close()
    }
    [Environment]::SetEnvironmentVariable('STOKE_PATH_CHANGED', '1', 'User')
    [Environment]::SetEnvironmentVariable('STOKE_PATH_CHANGED', $null, 'User')
    Write-Row 'command' 'stoke - on your PATH now; open a new terminal to use it'
  } catch {
    Write-Row 'command' "not added to PATH: $($_.Exception.Message)"
  }
}

# --- digests ---------------------------------------------------------------

# BASE64 of the raw 64-byte digest, which is the form electron-builder writes
# into latest.yml. NOT Get-FileHash, which emits hex: a hex string compared
# against the manifest never matches, and the failure reads exactly like a
# corrupted download.
function Get-Sha512Base64([string]$Path) {
  $sha = [Security.Cryptography.SHA512]::Create()
  try {
    $stream = [IO.File]::OpenRead($Path)
    try {
      return [Convert]::ToBase64String($sha.ComputeHash($stream))
    } finally {
      $stream.Dispose()
    }
  } finally {
    $sha.Dispose()
  }
}

# --- downloading -----------------------------------------------------------

# HttpClient with ResponseHeadersRead, deliberately not Invoke-WebRequest.
#
# Two reasons, and the first one is a hard block rather than a preference. Since
# CVE-2025-54100, Windows PowerShell 5.1's Invoke-WebRequest can raise an
# Internet Explorer first-launch prompt that a piped one-liner has no way to
# answer, unless -UseBasicParsing is passed - and the second reason is that it
# gives no byte-level progress at all, so there would be nothing for the fire to
# burn against.
function Get-StokeDownload([string]$Uri, [string]$OutFile, [int64]$Total, $Plan) {
  try { Add-Type -AssemblyName System.Net.Http -ErrorAction SilentlyContinue } catch { }
  $client = [Net.Http.HttpClient]::new()
  $client.Timeout = [TimeSpan]::FromMinutes(30)
  $opened = $false
  try {
    $resp = $client.GetAsync($Uri, [Net.Http.HttpCompletionOption]::ResponseHeadersRead).GetAwaiter().GetResult()
    if (-not $resp.IsSuccessStatusCode) {
      throw "The download failed: HTTP $([int]$resp.StatusCode) for $Uri. Nothing has been installed."
    }
    $in = $resp.Content.ReadAsStreamAsync().GetAwaiter().GetResult()
    $out = [IO.File]::Create($OutFile)
    $watch = [Diagnostics.Stopwatch]::StartNew()
    $lastDraw = -1
    $script:PlainLast = -1
    if ($Plan.Animate) { Open-Fire; $opened = $true }
    try {
      $buffer = New-Object byte[] 131072
      $done = [int64]0
      while ($true) {
        $read = $in.Read($buffer, 0, $buffer.Length)
        if ($read -le 0) { break }
        $out.Write($buffer, 0, $read)
        $done += $read
        $now = $watch.ElapsedMilliseconds
        if ($now - $lastDraw -ge $FireMs) {
          $lastDraw = $now
          Show-Progress -Done $done -Total $Total -Plan $Plan
        }
      }
      # The last reading belongs to the download being OVER, not to a tick
      # landing on the final byte.
      Show-Progress -Done $done -Total $Total -Plan $Plan -Final
    } finally {
      $out.Dispose()
      $in.Dispose()
    }
  } finally {
    if ($opened) { Reset-Fire }
    $client.Dispose()
  }
}

function Show-Progress([int64]$Done, [int64]$Total, $Plan, [switch]$Final) {
  if ($Plan.Animate) {
    $pct = 0
    if ($Total -gt 0) { $pct = [int][math]::Min(100, ($Done * 100) / $Total) }
    if ($Final) { $pct = 100 }
    Draw-Fire -Percent $pct -Mode $Plan.Color
    return
  }
  # The degraded path: one line per decile, append-only, no carriage return and
  # no escape byte, so a CI log and a support paste show the same thing
  # afterwards. With no total there is no percentage - just the megabytes. A
  # fabricated percent in a log somebody later reads back is worse than none.
  if ($Total -gt 0) {
    $decile = [int][math]::Min(10, [math]::Floor(($Done * 10) / $Total))
  } else {
    $decile = [int][math]::Floor($Done / 10000000)
  }
  if ($decile -le $script:PlainLast) { return }
  $script:PlainLast = $decile
  if ($Total -gt 0) {
    Write-Host ("  {0,5}  {1} MB" -f ("$($decile * 10)%"), (Format-Mb $Done))
  } else {
    Write-Host ("  {0,8} MB" -f (Format-Mb $Done))
  }
}

# --- the fire --------------------------------------------------------------

$script:FireOpen = $false
$script:PlainLast = -1

# Whether this console can render VT sequences at all - by TRYING to turn them
# on and believing SetConsoleMode, never by asking the OS version. A false
# positive prints `<esc>[38;2;255;149;82m` at somebody as the first thing Stoke
# ever does, which is the worst available first impression; and Add-Type failing
# under ConstrainedLanguage or AppLocker is an ordinary corporate way to land in
# exactly that ambiguity.
function Enable-VirtualTerminal {
  if ($PSVersionTable.PSVersion.Major -ge 6) { return $true }
  try {
    if (-not ('StokeVT.Native' -as [type])) {
      Add-Type -Namespace 'StokeVT' -Name 'Native' -MemberDefinition @'
[DllImport("kernel32.dll", SetLastError = true)] public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)] public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
[DllImport("kernel32.dll", SetLastError = true)] public static extern bool SetConsoleMode(IntPtr hConsoleHandle, uint dwMode);
'@ -ErrorAction Stop
    }
    $handle = [StokeVT.Native]::GetStdHandle(-11)
    $mode = [uint32]0
    if (-not [StokeVT.Native]::GetConsoleMode($handle, [ref]$mode)) { return $false }
    # ENABLE_VIRTUAL_TERMINAL_PROCESSING
    return [StokeVT.Native]::SetConsoleMode($handle, $mode -bor 0x0004)
  } catch {
    return $false
  }
}

# Whether to animate, and in which colour tier. The rules are the ones in
# src/shared/campfire.ts, plus the Windows-only VT probe above: a console that
# cannot do VT cannot redraw in place either, so that is a degraded reason and
# not merely a colour decision.
function Get-FirePlan {
  $reason = ''
  if ($env:STOKE_NO_ANIMATION) { $reason = 'STOKE_NO_ANIMATION is set' }
  elseif ([Console]::IsOutputRedirected) { $reason = 'stdout is not a terminal' }
  elseif ($env:CI -or $env:GITHUB_ACTIONS -or $env:TF_BUILD) { $reason = 'this is CI' }
  elseif (-not (Enable-VirtualTerminal)) { $reason = 'this console cannot render VT sequences' }

  if (-not $reason) {
    try {
      # Derived from $FireRows rather than hardcoded, for the reason install.sh
      # gives at the same test: the canvas has grown once already.
      $fireMin = $FireRows + 5
      if ([Console]::WindowHeight -lt $fireMin) { $reason = "the window is under $fireMin rows" }
      elseif ([Console]::WindowWidth -lt 20) { $reason = 'the window is under 20 columns' }
    } catch {
      # No console buffer to measure. Unknown is not a reason to degrade.
    }
  }

  if ($reason) {
    # A degraded console gets no colour TIER either, not merely no animation.
    return [pscustomobject]@{ Animate = $false; Color = 'none'; Reason = $reason }
  }

  # NO_COLOR governs colour, not motion: no-color.org says the variable "when
  # present and not an empty string" prevents ANSI colour, and says nothing
  # whatever about animation. The art is a silhouette and reads perfectly in one
  # colour, so the fire still burns.
  $color = 'ansi16'
  if ($env:NO_COLOR) {
    $color = 'none'
  } elseif ($env:WT_SESSION) {
    $color = 'truecolor'
  } elseif ($env:COLORTERM -and ($env:COLORTERM -match '(?i)truecolor|24bit')) {
    $color = 'truecolor'
  }
  # TERM is deliberately not consulted on Windows: the console host rounds
  # anything richer than its own sixteen colours to the nearest of them, and
  # #e85f24, #ff9552 and #ffc48c are close enough that it can collapse all three
  # into one red. The 16-colour tier is a hand-tuned choice here, not a
  # degradation.
  return [pscustomobject]@{ Animate = $true; Color = $color; Reason = '' }
}

# Frame $n as seven rows joined by newlines, coloured, with no cursor movement
# in it. The caller owns the redraw.
function Get-FireFrame([int]$Index, [string]$Mode) {
  if ($Mode -eq 'none') { return ($FireM[$Index] + "`n" + $FireMH) }
  $table = $FireSgr[$Mode]
  $rows = @()
  foreach ($line in (($FireF[$Index] + "`n" + $FireFH) -split "\r?\n")) {
    $out = ''
    $active = ''
    if ($line -ne '') {
      foreach ($seg in ($line -split '\|')) {
        # Segments are KEY:text. Neither delimiter can appear in the art, so
        # the split is unambiguous.
        $key = $seg.Substring(0, 1)
        $text = $seg.Substring(2)
        if ($key -ne '_') {
          $seq = [string]$table[$key]
          # A sequence equal to the one in effect is skipped, and a run of
          # spaces emits none and does not end it. Only the foreground is ever
          # set, so that is safe.
          if ($seq -ne $active) { $out += $Esc + $seq; $active = $seq }
        }
        $out += $text
      }
    }
    # Every painted row ends with a reset: a live foreground across the newline
    # would colour whatever the installer prints next.
    if ($active -ne '') { $out += $Esc + $FireReset }
    $rows += $out
  }
  return ($rows -join "`n")
}

# Hide the cursor and make the canvas exist before drawing into it, so whatever
# scrolling is going to happen has already happened and "up $FireRows" is right
# from the first frame on.
function Open-Fire {
  $script:FireOpen = $true
  $script:FireTick = 0
  [Console]::Out.Write("$Esc[?25l")
  [Console]::Out.Write(("`n" * $FireRows))
}

# Never the alternate screen buffer: leaving it restores the previous one, so
# everything the installer printed - where the app went, what was cleared -
# would be gone the instant it exits, along with the scrollback of anyone
# reading back what an `iex` just did.
function Draw-Fire([int]$Percent, [string]$Mode) {
  $stage = 0
  foreach ($threshold in $FireStagePct) { if ($Percent -ge $threshold) { $stage++ } }
  $flicker = $FireFlicker[$script:FireTick % $FireFlicker.Count]
  $frame = Get-FireFrame -Index (($stage * $FireStride) + $flicker) -Mode $Mode
  # Up $FireRows, then every row prefixed with erase-in-line: three bytes, and
  # correct at any window width where padding to 15 columns would not be.
  $text = "$Esc[$($FireRows)A"
  foreach ($row in ($frame -split "\r?\n")) { $text += "$Esc[K$row`n" }
  # [Console]::Out.Write, never Write-Host: $PSStyle.OutputRendering strips
  # escape sequences out of anything PowerShell formats.
  [Console]::Out.Write($text)
  $script:FireTick++
}

# Cursor FIRST, before anything else that could itself fail, and idempotent
# because the finally blocks above all call it.
function Reset-Fire {
  if (-not $script:FireOpen) { return }
  $script:FireOpen = $false
  try { [Console]::Out.Write("$Esc[?25h$Esc$FireReset") } catch { }
}

$script:FireTick = 0

Install-Stoke
