/*
 * Print the campfire art block the installers carry, from src/shared/campfire.ts.
 *
 *   node scripts/gen-installer-art.mts sh    > the block for install/install.sh
 *   node scripts/gen-installer-art.mts ps1   > the block for install/install.ps1
 *   node scripts/gen-installer-art.mts --all
 *
 * Same arrangement as scripts/gen-themes.mts and verify:theme-gen (gotcha 43):
 * the generator is the only way the art is produced, and verify:campfire asserts
 * the checked-in block still equals this output byte for byte. That is not
 * ceremony — the segment encoding was hand-written once while the art was being
 * designed and shipped two malformed rows (`(|#|=|` and a stray trailing pair)
 * into a running script, which printed a literal `||` at the user and were found
 * only by reading a real run's output. A block nobody may hand-edit, plus a
 * decode(encode(x)) === x assertion, is the only defence against that class.
 *
 * The block is delimited by BEGIN/END sentinel comments so the installer can
 * carry it verbatim in a file that is otherwise hand-written, and so the suite
 * can slice exactly the generated part out again. `#` is a comment in both a
 * POSIX shell and PowerShell, so one sentinel text serves both.
 *
 * What the block contains, and why both forms of the art are in it:
 *   FIRE_F0..FIRE_F11 / $FireF0..  segment-encoded flame rows, KEY:text|KEY:text.
 *                                  The colour is resolved at generation time so
 *                                  the draw loop forks nothing — per-glyph colour
 *                                  otherwise means an awk or sed per frame, eight
 *                                  times a second, beside a download.
 *   FIRE_M0..FIRE_M11 / $FireM0..  the same rows, plain. Monochrome is a real
 *                                  tier (NO_COLOR, and bare conhost when VT could
 *                                  not be enabled), and it should be the simplest
 *                                  path in the script rather than a decode loop.
 *                                  Costs 539 bytes; buys a path that cannot be
 *                                  got wrong.
 *   FIRE_FH / FIRE_MH              the two hearth rows, stored once because they
 *                                  are byte-identical under all twelve frames.
 *   SGR_*                          the palette, as the bytes AFTER ESC.
 */
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import {
  CANVAS,
  FLICKER,
  FRAME_MS,
  HEARTH,
  RESET,
  SGR,
  STAGES,
  STAGE_THRESHOLDS,
  encodeRow,
  type ColorKey,
  type ColorMode
} from '../src/shared/campfire.ts'

export const BEGIN_MARK = '# BEGIN CAMPFIRE ART'
export const END_MARK = '# END CAMPFIRE ART'

/** The twelve frames in draw order: stage * 3 + flicker. */
function flameFrames(): string[][] {
  return STAGES.flatMap((stage) => stage.frames.map((rows) => [...rows]))
}

/**
 * The stage thresholds as whole percentages. A POSIX shell has no floating
 * point, so the script compares integers; asserting they ARE integers here is
 * what stops a future 0.125 threshold from being silently truncated to 12.
 */
function stagePercents(): number[] {
  return STAGE_THRESHOLDS.map((t) => {
    const pct = t * 100
    if (!Number.isInteger(pct)) {
      throw new Error(`campfire: stage threshold ${t} is not a whole percentage; a POSIX shell cannot compare it`)
    }
    return pct
  })
}

const PAINTED_KEYS: ColorKey[] = ['C', 'S', 'M', 'B', 'L']
const MODE_VAR: Record<Exclude<ColorMode, 'none'>, string> = {
  truecolor: 'TC',
  ansi256: 'X2',
  ansi16: 'A1'
}

/**
 * How many flicker frames a stage has. Read off the stages rather than inferred
 * from FLICKER's length, because the two are different numbers that happen to
 * relate: the preamble documents `n = stage * <this> + flicker`, and a stage
 * that grew a fourth frame while the text still said three would hand the
 * installer an index formula that silently addresses the wrong frame.
 */
function flickerFrames(): number {
  const counts = [...new Set(STAGES.map((s) => s.frames.length))]
  if (counts.length !== 1) {
    throw new Error(`campfire: stages have ${counts.join('/')} frames each; the block's index formula assumes one count`)
  }
  return counts[0]
}

/**
 * The shared explanation, as comment lines without their leading `#`. Everything
 * it names has to be spelled the way THIS block spells it: the block is the
 * contract the installer is written against, so a ps1 preamble naming
 * `FIRE_STAGE_PCT` and telling its reader to reach for `printf` is a wrong
 * instruction in a file nobody is allowed to correct by hand.
 */
function preamble(kind: 'sh' | 'ps1'): string[] {
  const sh = kind === 'sh'
  const n = flickerFrames()
  return [
    'Generated by `node scripts/gen-installer-art.mts ' + kind + '` from src/shared/campfire.ts.',
    'DO NOT EDIT BY HAND: verify:campfire asserts this block byte for byte against',
    'the generator, and a hand-encoded row has already shipped a visible `||` once.',
    '',
    `Canvas is a fixed ${CANVAS.rows} rows x ${CANVAS.cols} columns for every frame, because redraw in`,
    `place is ESC[${CANVAS.rows}A and nothing else -- a shorter frame walks the cursor up the`,
    'screen a row per tick. Flame rows are stored right-trimmed; emit ESC[K per row',
    'rather than padding to the full width.',
    '',
    `${flameFrames().length} frames: ${STAGES.length} stages (${STAGES.map((s) => s.name).join(' ')}) x ${n} flicker frames.`,
    `Pick with: stage from ${sh ? 'FIRE_STAGE_PCT' : '$FireStagePct'} against the percentage downloaded,`,
    `flicker from ${sh ? `FIRE_FLICKER[tick % ${FLICKER.length}]` : `$FireFlicker[$tick % ${FLICKER.length}]`}, then n = stage * ${n} + flicker and`,
    sh ? '  eval "rows=\\$FIRE_F$n"    (or FIRE_M$n for the monochrome tier).' : '  $FireF[$n]                (or $FireM[$n] for the monochrome tier).',
    '',
    'Rows are segment-encoded as KEY:text|KEY:text, joined by newlines. Keys:',
    '  _ uncoloured (spaces)   C core (white-hot)   S spark   M mid   B base   L log',
    'Neither | nor : can appear in the art, so the split is unambiguous.',
    `${sh ? 'FIRE_M*' : '$FireM*'} is the same art with no colour at all, for the monochrome tier.`,
    '',
    ...(sh
      ? [
          'Print these with a literal format string -- printf \'%s\' "$row", never',
          'printf "$row" -- the art is full of backslashes and % is not escaped here.'
        ]
      : [
          'Print these with [Console]::Out.Write($row), never Write-Host and never a',
          'format operator -- $PSStyle.OutputRendering strips escape sequences from',
          'anything PowerShell formats, and the art is full of backslashes.'
        ])
  ]
}

/** The art block for a POSIX shell, between its sentinels. */
export function shArtBlock(): string {
  const out: string[] = [BEGIN_MARK, ...preamble('sh').map((l) => (l ? `# ${l}` : '#'))]
  out.push(
    `FIRE_ROWS=${CANVAS.rows}`,
    `FIRE_COLS=${CANVAS.cols}`,
    `FIRE_MS=${FRAME_MS}`,
    `FIRE_FLICKER='${FLICKER.join(' ')}'`,
    `FIRE_STAGE_PCT='${stagePercents().join(' ')}'`
  )
  const frames = flameFrames()
  frames.forEach((rows, i) => {
    out.push(`FIRE_F${i}='${rows.map((r, y) => encodeRow(r, y)).join('\n')}'`)
  })
  out.push(`FIRE_FH='${HEARTH.map((r, y) => encodeRow(r, y + 5)).join('\n')}'`)
  frames.forEach((rows, i) => {
    out.push(`FIRE_M${i}='${rows.join('\n')}'`)
  })
  out.push(`FIRE_MH='${HEARTH.join('\n')}'`)
  out.push(
    '# The palette, as the bytes AFTER ESC. ESC itself comes from `printf \'\\033\'`',
    '# -- octal, because \\e is a bash/zsh extension that dash and busybox ash lack.'
  )
  for (const mode of Object.keys(MODE_VAR) as Exclude<ColorMode, 'none'>[]) {
    for (const key of PAINTED_KEYS) out.push(`SGR_${MODE_VAR[mode]}_${key}='${SGR[mode][key]}'`)
  }
  out.push(`SGR_RESET='${RESET}'`, END_MARK)
  return out.join('\n') + '\n'
}

/** The same data for PowerShell. Here-strings, so the art needs no escaping. */
export function ps1ArtBlock(): string {
  const out: string[] = [BEGIN_MARK, ...preamble('ps1').map((l) => (l ? `# ${l}` : '#'))]
  out.push(
    `$FireRows = ${CANVAS.rows}`,
    `$FireCols = ${CANVAS.cols}`,
    `$FireMs = ${FRAME_MS}`,
    `$FireFlicker = @(${FLICKER.join(', ')})`,
    `$FireStagePct = @(${stagePercents().join(', ')})`
  )
  const frames = flameFrames()
  const here = (name: string, body: string): void => {
    // The opener must end its line and the terminator must start one, with
    // nothing before it -- hence one variable per here-string rather than the
    // array literal, which would put `'@,` at the start of a line.
    out.push(`$${name} = @'`, body, `'@`)
  }
  frames.forEach((rows, i) => here(`FireF${i}`, rows.map((r, y) => encodeRow(r, y)).join('\n')))
  here('FireFH', HEARTH.map((r, y) => encodeRow(r, y + 5)).join('\n'))
  frames.forEach((rows, i) => here(`FireM${i}`, rows.join('\n')))
  here('FireMH', HEARTH.join('\n'))
  out.push(`$FireF = @(${frames.map((_, i) => `$FireF${i}`).join(', ')})`)
  out.push(`$FireM = @(${frames.map((_, i) => `$FireM${i}`).join(', ')})`)
  out.push(
    '# The palette, as the bytes AFTER ESC. ESC itself is [char]27; write it with',
    '# [Console]::Out.Write, never Write-Host -- $PSStyle.OutputRendering strips',
    '# escape sequences from anything PowerShell formats.'
  )
  out.push('$FireSgr = @{')
  for (const mode of Object.keys(MODE_VAR) as Exclude<ColorMode, 'none'>[]) {
    const pairs = PAINTED_KEYS.map((k) => `${k} = '${SGR[mode][k]}'`).join('; ')
    out.push(`  ${mode} = @{ ${pairs} }`)
  }
  out.push('}', `$FireReset = '${RESET}'`, END_MARK)
  return out.join('\n') + '\n'
}

/**
 * The generated block out of a file that carries it, or null when the file has
 * no sentinels. Returned WITH both sentinel lines, so a comparison covers them.
 */
export function extractBlock(text: string): string | null {
  const begin = text.indexOf(BEGIN_MARK)
  const end = text.indexOf(END_MARK)
  if (begin < 0 || end < 0 || end < begin) return null
  return text.slice(begin, end + END_MARK.length) + '\n'
}

const isMain = process.argv[1] ? resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false
if (isMain) {
  const want = process.argv[2]
  const all = want === '--all'
  if (all || want === 'sh') process.stdout.write(shArtBlock())
  if (all || want === 'ps1') process.stdout.write(ps1ArtBlock())
  if (!all && want !== 'sh' && want !== 'ps1') {
    console.error('usage: node scripts/gen-installer-art.mts sh|ps1|--all')
    process.exitCode = 2
  }
}
