import assert from 'node:assert/strict'
import { TabWindowState } from '../src/main/tabWindowState.ts'
import { canMoveTab, tabDragLeavesStrip, type Tab, type TabWindowPacket } from '../src/shared/tabWindows.ts'
import { nativeRevealOffset } from '../src/shared/nativeReveal.ts'
import { restorableTabs, toStored } from '../src/renderer/src/lib/restore.ts'

const tab = (id: string): Tab => ({ id, kind: 'session', cliId: 'codex', accountId: 'codex-work', ptyId: `pty-${id}`, sessionId: `session-${id}`, cwd: '/fixture', projectName: 'Fixture', title: id, permissionMode: 'default', model: '', effort: 'default', ultracode: false, status: 'running', exitCode: null, hostId: null, selectedPath: null, expandedPath: null })
const packet = (tabs: Tab[]): TabWindowPacket => ({ tabs, activeId: tabs[0]?.id ?? null, contexts: {}, drafts: {}, screens: {}, stored: { state: toStored(tabs, tabs[0]?.id ?? null, {}, () => 'fixture screen', 10), ids: restorableTabs(tabs).map(t => t.id) } })
const a = tab('a'), b = tab('b'), c = tab('c')
const state = new TabWindowState()
assert(state.publish(1, [a, b]))
assert(state.publish(2, []))
assert(state.stage('move', 1, 2, packet([a])))
assert.deepEqual(state.tabs.get(1)?.map(t => t.id), ['a', 'b'], 'a loading window cannot remove the source tab')
assert(!state.stage('duplicate', 1, 3, packet([a])), 'double detach is claimed before load')
assert(!state.stage('second-tab', 1, 3, packet([b])), 'one source handoff at a time keeps the renderer guard scoped')
assert.equal(state.accept('move', 3), null, 'only the intended target may accept')
assert.equal(state.accept('move', 2)?.source, 1)
assert.deepEqual(state.tabs.get(1)?.map(t => t.id), ['b'])
assert.deepEqual(state.tabs.get(2)?.map(t => t.id), ['a'])
assert.equal(state.tabs.get(2)?.[0].ptyId, a.ptyId, 'the same PTY, never a replacement launch')
assert.equal(state.tabs.get(2)?.[0].accountId, 'codex-work', 'launch account survives the move')
assert(!state.publish(1, [a, b]), 'a late source render cannot claim a transferred tab')
assert.equal(state.accept('move', 2), null, 'duplicate acknowledgement cannot copy a session')
assert(state.stage('return', 2, 1, packet([a])))
assert(state.accept('return', 1))
assert.deepEqual(state.tabs.get(1)?.map(t => t.id), ['b', 'a'])
assert(state.publish(3, [c]))
assert(state.stage('failed', 3, 4, packet([c])))
state.remove(4)
assert.equal(state.pending.size, 0)
assert.deepEqual(state.tabs.get(3), [c], 'a failed target leaves the source intact')
assert(!state.stage('foreign', 1, 3, packet([c])))
assert(!state.stage('changed', 1, 3, packet([{ ...a, ptyId: 'different-child' }])))
assert(!state.publish(4, [{ id: 'bad' }]))
assert(!state.publish(4, [c, c]))
assert(canMoveTab({ ...a, hostId: 'fixture-ssh' }))
assert(canMoveTab({ ...a, private: true }))
assert(!canMoveTab({ ...a, installing: ['codex'] }))
assert(!canMoveTab({ ...a, accountLogin: 'codex-work' }))
assert(!canMoveTab({ ...a, reconnect: { attempt: 1, at: 10 } }))
assert(!canMoveTab({ ...a, kind: 'remote' }))
assert.equal(packet([{ ...a, private: true }]).stored.state.tabs.length, 0, 'a private terminal may move in memory but never to the restore file')
assert.equal(packet([{ ...a, private: true }, b]).stored.ids[0], b.id)
assert(!tabDragLeavesStrip(70, 0, 44), 'ordinary tab clicks and reorders never tear off')
assert(tabDragLeavesStrip(82, 0, 44))
assert(tabDragLeavesStrip(-40, 0, 44))
assert(!tabDragLeavesStrip(NaN, 0, 44))
console.log('PASS tab handoff: ownership, duplicate/late acknowledgements, failed windows, account and private restore scope')

const bounds = { x: 0, y: 0, width: 1440, height: 900 }
const frame = (y: number, extra = {}) => ({ x: 0, y, width: 1440, height: 62, onscreen: true, ...extra })
assert.equal(nativeRevealOffset([frame(-62)], bounds, 62), 0)
assert.equal(nativeRevealOffset([frame(-45)], bounds, 62), 17, 'follows the actual reveal during its slide')
assert.equal(nativeRevealOffset([frame(0)], bounds, 62), 62)
assert.equal(nativeRevealOffset([frame(-26)], bounds, 62), 36, 'hide follows the native slide without a second linger')
assert.equal(nativeRevealOffset([frame(0, { onscreen: false })], bounds, 62), 0)
assert.equal(nativeRevealOffset([frame(0, { width: 400 })], bounds, 62), 0, 'notification-sized windows do not reveal the shell')
assert.equal(nativeRevealOffset([frame(0, { x: 1440 })], bounds, 62), 0, 'a menu on another display does not move this window')
assert.equal(nativeRevealOffset([frame(0)], { ...bounds, y: 30 }, 32), 32, 'a window already under the menu follows only the native title strip')
assert.equal(nativeRevealOffset(null, bounds, 62), null)
assert.equal(nativeRevealOffset([{ width: 'bad' }], bounds, 62), null)
assert.equal(nativeRevealOffset([], bounds, 62), 0)
assert.equal(nativeRevealOffset(Array(129).fill(frame(0)), bounds, 62), null)
console.log('PASS native reveal geometry: partial slides, hidden menu, notch/inset, other displays and unavailable metadata')
